### ISSUE TITLE
Podcats error

### ISSUE THREAD

**Issue by Code-Slave** [airsonic/airsonic#1013]
https://rss.art19.com/over-my-dead-body

## Problem description

This specific podcast throws an error trying to dl the mp3. 

### Steps to reproduce
Subscribe to the podcast in airsonic

## System information
latest docker image

errors:

```java
org.apache.http.client.ClientProtocolException: null
--
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187) ~[httpclient-4.5.6.jar!/:4.5.6]
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.6.jar!/:4.5.6]
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.6.jar!/:4.5.6]
at org.airsonic.player.service.PodcastService.doDownloadEpisode(PodcastService.java:560) [classes!/:10.2.1-RELEASE]
at org.airsonic.player.service.PodcastService.access$300(PodcastService.java:72) [classes!/:10.2.1-RELEASE]
at org.airsonic.player.service.PodcastService$5.run(PodcastService.java:413) [classes!/:10.2.1-RELEASE]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_201]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_201]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
Caused by:  org.apache.http.client.CircularRedirectException: Circular redirect to  'https://rss.art19.com/episodes/56e5b014-4a44-4a19-83a0-4d364da922ca.mp3'
at  org.apache.http.impl.client.DefaultRedirectStrategy.getLocationURI(DefaultRedirectStrategy.java:177)  ~[httpclient-4.5.6.jar!/:4.5.6]
at  org.apache.http.impl.client.DefaultRedirectStrategy.getRedirect(DefaultRedirectStrategy.java:221)  ~[httpclient-4.5.6.jar!/:4.5.6]
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:121) ~[httpclient-4.5.6.jar!/:4.5.6]
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.6.jar!/:4.5.6]
... 10 common frames omitted
 
2019-04-13 11:38:58.526  WARN ---  o.a.h.c.p.ResponseProcessCookies         : Invalid cookie header:  "Set-Cookie:  art19_episode_tracking=bXVmQyswcHUwbWVHcHJzbmxCamd2QkFieTRXQXpIemJ6bGVUekpsaVBkQ2V1czRUYUt5WHh6M3JBcEpOSkcyQi0tNE9BU0lheEpvaEdJVGZFelR6V09yUT09--814f45fb5172f2b49a414b6c74885fe63ff0b19f;  path=/; expires=Wed, 13 Apr 2039 15:38:58 -0000". Invalid 'expires'  attribute: Wed, 13 Apr 2039 15:38:58 -0000
2019-04-13 11:38:58.528  WARN ---  o.a.p.service.PodcastService             : Failed to download Podcast  from  https://dts.podtrac.com/redirect.mp3/chtbl.com/track/9EE2G/rss.art19.com/episodes/ccae3cc4-9ccd-4fa8-9bdc-44ab434390f6.mp3
 
```

**Comment by jvoisin** [comment]
According to your logs, it looks like the problem might come from the podcast and not from airsonic.

**Comment by Code-Slave** [comment]
it looks like it cant handle the tracking redirect

**Comment by eharris** [comment]
PR #1175 fixes this issue by enabling circular redirects on the download HttpClient connection, since some podcast urls use them.

The same PR also addresses the `Invalid cookie header` ... `Invalid 'expires' attribute` error that is also shown in this problem report by enabling `CookieSpecs.STANDARD` cookie handling.

More info about the cookie expires issue can be found at the following:
https://stackoverflow.com/questions/36473478/fixing-httpclient-warning-invalid-expires-attribute-using-fluent-api
