### ISSUE TITLE
Java error cannot start

### ISSUE THREAD

**Issue by galosre** [airsonic/airsonic#1108]
ON openmediavault docker 
linuxserver/airsonic
Getting a java error

```java
           _                       _
     /\   (_)                     (_)
    /  \   _ _ __  ___  ___  _ __  _  ___
   / /\ \ | | '__|/ __|/ _ \| '_ \| |/ __|
  / ____ \| | |   \__ \ (_) | | | | | (__
 /_/    \_\_|_|   |___/\___/|_| |_|_|\___|

                        10.3.1-RELEASE



2019-06-08 14:00:39.394  INFO --- org.airsonic.player.Application          : Starting Application v10.3.1-RELEASE on 7e37946ac671 with PID 414 (/app/airsonic/airsonic.war started by abc in /app/airsonic)
2019-06-08 14:00:39.409  INFO --- org.airsonic.player.Application          : The following profiles are active: legacy
2019-06-08 14:00:48.540  INFO --- o.a.p.service.SettingsService            : Java: 1.8.0_212, OS: Linux
2019-06-08 14:00:49.750  INFO --- org.airsonic.player.Application          : Detected Tomcat web server
2019-06-08 14:00:55.059 ERROR --- o.a.catalina.core.ContainerBase          : A child container failed during start

java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.8.0_212]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) [na:1.8.0_212]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:942) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:872) [tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1423) [tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1413) [tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167) [tomcat-embed-core-8.5.40.jar!/:8.5.40]
	... 6 common frames omitted
Caused by: java.lang.IllegalStateException: java.util.zip.ZipException: invalid entry CRC (expected 0x2e4aa7a9 but got 0xc0e0d439)
	at org.apache.catalina.webresources.JarWarResourceSet.getArchiveEntries(JarWarResourceSet.java:148) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:254) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.webresources.StandardRoot.getResourcesInternal(StandardRoot.java:327) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.webresources.CachedResource.validateResources(CachedResource.java:140) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.webresources.Cache.getResources(Cache.java:147) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.webresources.StandardRoot.getResources(StandardRoot.java:315) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.webresources.StandardRoot.getClassLoaderResources(StandardRoot.java:231) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.util.ExtensionValidator.validateApplication(ExtensionValidator.java:146) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5040) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.40.jar!/:8.5.40]
	... 6 common frames omitted
Caused by: java.util.zip.ZipException: invalid entry CRC (expected 0x2e4aa7a9 but got 0xc0e0d439)
	at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:394) ~[na:1.8.0_212]
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:196) ~[na:1.8.0_212]
	at java.util.jar.JarInputStream.read(JarInputStream.java:207) ~[na:1.8.0_212]
	at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:140) ~[na:1.8.0_212]
	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:118) ~[na:1.8.0_212]
	at java.util.jar.JarInputStream.getNextEntry(JarInputStream.java:142) ~[na:1.8.0_212]
	at java.util.jar.JarInputStream.getNextJarEntry(JarInputStream.java:179) ~[na:1.8.0_212]
	at org.apache.catalina.webresources.JarWarResourceSet.getArchiveEntries(JarWarResourceSet.java:117) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	... 15 common frames omitted

2019-06-08 14:00:55.070 ERROR --- o.a.catalina.core.ContainerBase          : A child container failed during start

java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_212]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_212]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:942) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262) [tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422) [tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:793) [tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:427) [tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.initialize(TomcatEmbeddedServletContainer.java:114) [spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.<init>(TomcatEmbeddedServletContainer.java:87) [spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getTomcatEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:560) [spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:179) [spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:166) [spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:136) [spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536) [spring-context-4.3.23.RELEASE.jar!/:4.3.23.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:124) [spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	at org.airsonic.player.Application.main(Application.java:229) [classes!/:10.3.1-RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [airsonic.war:10.3.1-RELEASE]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [airsonic.war:10.3.1-RELEASE]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [airsonic.war:10.3.1-RELEASE]
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) [airsonic.war:10.3.1-RELEASE]
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167) [tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1423) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1413) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]
Caused by: org.apache.catalina.LifecycleException: A child container failed during start
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:953) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:872) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.40.jar!/:8.5.40]
	... 6 common frames omitted
Caused by: java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_212]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_212]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:942) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	... 8 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167) [tomcat-embed-core-8.5.40.jar!/:8.5.40]
	... 6 common frames omitted
Caused by: java.lang.IllegalStateException: java.util.zip.ZipException: invalid entry CRC (expected 0x2e4aa7a9 but got 0xc0e0d439)
	at org.apache.catalina.webresources.JarWarResourceSet.getArchiveEntries(JarWarResourceSet.java:148) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:254) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.webresources.StandardRoot.getResourcesInternal(StandardRoot.java:327) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.webresources.CachedResource.validateResources(CachedResource.java:140) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.webresources.Cache.getResources(Cache.java:147) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.webresources.StandardRoot.getResources(StandardRoot.java:315) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.webresources.StandardRoot.getClassLoaderResources(StandardRoot.java:231) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.util.ExtensionValidator.validateApplication(ExtensionValidator.java:146) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5040) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.40.jar!/:8.5.40]
	... 6 common frames omitted
Caused by: java.util.zip.ZipException: invalid entry CRC (expected 0x2e4aa7a9 but got 0xc0e0d439)
	at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:394) ~[na:1.8.0_212]
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:196) ~[na:1.8.0_212]
	at java.util.jar.JarInputStream.read(JarInputStream.java:207) ~[na:1.8.0_212]
	at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:140) ~[na:1.8.0_212]
	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:118) ~[na:1.8.0_212]
	at java.util.jar.JarInputStream.getNextEntry(JarInputStream.java:142) ~[na:1.8.0_212]
	at java.util.jar.JarInputStream.getNextJarEntry(JarInputStream.java:179) ~[na:1.8.0_212]
	at org.apache.catalina.webresources.JarWarResourceSet.getArchiveEntries(JarWarResourceSet.java:117) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	... 15 common frames omitted

2019-06-08 14:00:55.091  WARN --- ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
2019-06-08 14:00:55.831 ERROR --- o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:139) ~[spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536) ~[spring-context-4.3.23.RELEASE.jar!/:4.3.23.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:124) ~[spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) ~[spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) ~[spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	at org.airsonic.player.Application.main(Application.java:229) [classes!/:10.3.1-RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [airsonic.war:10.3.1-RELEASE]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [airsonic.war:10.3.1-RELEASE]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [airsonic.war:10.3.1-RELEASE]
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) [airsonic.war:10.3.1-RELEASE]
Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.initialize(TomcatEmbeddedServletContainer.java:138) ~[spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.<init>(TomcatEmbeddedServletContainer.java:87) ~[spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getTomcatEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:560) ~[spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:179) ~[spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:166) ~[spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:136) ~[spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	... 15 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardServer[-1]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:427) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.initialize(TomcatEmbeddedServletContainer.java:114) ~[spring-boot-1.5.20.RELEASE.jar!/:1.5.20.RELEASE]
	... 20 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardService[Tomcat]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:793) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	... 22 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	... 24 common frames omitted
Caused by: org.apache.catalina.LifecycleException: A child container failed during start
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:953) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	... 26 common frames omitted
Caused by: java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_212]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_212]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:942) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	... 28 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1423) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1413) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]
Caused by: org.apache.catalina.LifecycleException: A child container failed during start
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:953) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:872) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	... 6 common frames omitted
Caused by: java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_212]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_212]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:942) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	... 8 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	... 6 common frames omitted
Caused by: java.lang.IllegalStateException: java.util.zip.ZipException: invalid entry CRC (expected 0x2e4aa7a9 but got 0xc0e0d439)
	at org.apache.catalina.webresources.JarWarResourceSet.getArchiveEntries(JarWarResourceSet.java:148) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:254) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.webresources.StandardRoot.getResourcesInternal(StandardRoot.java:327) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.webresources.CachedResource.validateResources(CachedResource.java:140) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.webresources.Cache.getResources(Cache.java:147) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.webresources.StandardRoot.getResources(StandardRoot.java:315) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.webresources.StandardRoot.getClassLoaderResources(StandardRoot.java:231) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.util.ExtensionValidator.validateApplication(ExtensionValidator.java:146) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5040) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	... 6 common frames omitted
Caused by: java.util.zip.ZipException: invalid entry CRC (expected 0x2e4aa7a9 but got 0xc0e0d439)
	at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:394) ~[na:1.8.0_212]
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:196) ~[na:1.8.0_212]
	at java.util.jar.JarInputStream.read(JarInputStream.java:207) ~[na:1.8.0_212]
	at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:140) ~[na:1.8.0_212]
	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:118) ~[na:1.8.0_212]
	at java.util.jar.JarInputStream.getNextEntry(JarInputStream.java:142) ~[na:1.8.0_212]
	at java.util.jar.JarInputStream.getNextJarEntry(JarInputStream.java:179) ~[na:1.8.0_212]
	at org.apache.catalina.webresources.JarWarResourceSet.getArchiveEntries(JarWarResourceSet.java:117) ~[tomcat-embed-core-8.5.40.jar!/:8.5.40]
	... 15 common frames omitted

           _                       _
     /\   (_)                     `(_)
```

**Comment by jooola** [comment]
Could you please open a ticket to the owner of the linuxserver airsonic docker image, we don't maintain this image.

I'm not sure to know what openmediavault is, but did you tried the official airsonic image ?

**Comment by jvoisin** [comment]
I looks like a corrupted .jar, did you check the gpg signature?
