### ISSUE TITLE
LDAP: allow subtree search for user object

### ISSUE THREAD

**Issue by Daryes** [airsonic/airsonic#1141]
## Problem description
When defining the LDAP url connection on an Active Directory server, using only the root context leads to an internal error :
```
org.springframework.security.authentication.InternalAuthenticationServiceException: invalid attribute description; nested exception is javax.naming.directory.InvalidSearchFilterException: invalid attribute description; remaining name ''
        at org.springframework.security.ldap.authentication.LdapAuthenticationProvider.doAuthentication(LdapAuthenticationProvider.java:206) ~[spring-security-ldap-4.2.12.RELEASE.jar!/:4.2.12.RELEASE]
        at org.springframework.security.ldap.authentication.AbstractLdapAuthenticationProvider.authenticate(AbstractLdapAuthenticationProvider.java:85) ~[spring-security-ldap-4.2.12.RELEASE.jar!/:4.2.12.RELEASE]
```
This is related to the fact that the ldap connector expects a user object directly at the target.

In short, this doesn't work : `LdapUrl=ldap://server:389/DC=domain,DC=tld`  
while this will be OK : `LdapUrl=ldap://server:389/OU=users,DC=domain,DC=tld`  
The problem with the second method is even when LdapSearchFilter is restricted to looking for a specific group membership, users won't be returned when in a different OU at the same level .

There are 2 options allowing to use the root definition while filtering with group membership : 
* using the sub parameter in the query : `ldap://server:389/DC=domain,DC=tld??sub?( <ldap query> )`
* specifying `SearchControls.SUBTREE_SCOPE` when configuring the java object.

I haven't been able to make the sub parameter work with airsonic, while I could validate both behaviors with Apache Directory Studio (and also getting the same errors)

Would it be possible to have a new parameter in `airsonic.properties` like `LdapSearchSubtree` which will activate the SUBTREE_SCOPE setting in the ldap url search ?

## System information

 * **Airsonic version**: 10.3.1
 * **Operating system**: Ubuntu 16.04
 * **Java version**:  OpenJDK 1.8.0_212
 * **Proxy server**: 
 * **Client**: Firefox

**Comment by jvoisin** [comment]
This sounds like a valid suggestion.
I don't plan on implementing it any time soon, if at all, but I'll be happy to review'n'merge a pull-request :)
