### ISSUE TITLE
LDAP manager password fails to decode

### ISSUE THREAD

**Issue by joshuaboniface** [airsonic/airsonic#1375]
## Problem description

Starting Airsonic 10.4.1 with LDAP support fails due to the following error:

```
Oct 24 22:22:37 sonic1.i.net java[7926]: 2019-10-24 22:22:37.605  WARN --- o.a.p.service.SettingsService            : Failed to decode LDAP manager password.                                                                          
Oct 24 22:22:37 sonic1.i.net java[7926]: org.apache.commons.codec.DecoderException: Illegal hexadecimal character " at index 0                                                                                                   
Oct 24 22:22:37 sonic1.i.net java[7926]:         at org.apache.commons.codec.binary.Hex.toDigit(Hex.java:178) ~[commons-codec-1.10.jar!/:1.10]                                                                                         Oct 24 22:22:37 sonic1.i.net java[7926]:         at org.apache.commons.codec.binary.Hex.decodeHex(Hex.java:89) ~[commons-codec-1.10.jar!/:1.10]                                                           
Oct 24 22:22:37 sonic1.i.net java[7926]:         at org.airsonic.player.util.StringUtil.utf8HexDecode(StringUtil.java:407) ~[classes!/:10.4.1-RELEASE]                                                                                 
Oct 24 22:22:37 sonic1.i.net java[7926]:         at org.airsonic.player.service.SettingsService.getLdapManagerPassword(SettingsService.java:684) ~[classes!/:10.4.1-RELEASE]                                                          
Oct 24 22:22:37 sonic1.i.net java[7926]:         at org.airsonic.player.security.GlobalSecurityConfig.configureGlobal(GlobalSecurityConfig.java:59) [classes!/:10.4.1-RELEASE]                                                         
```

This occurs with or without quotes around the password; without quotes, it fails on the first non-hex character. It looks like Airsonic is expecting this password to be in hexidecimal formatting, which seems strange. If I manually save the password I get back a simple hex encoding of the password string.

### Steps to reproduce

Use a plaintext password in airsonic.properties for LdapManagerPassword.

## System information

 * **Airsonic version**: 10.4.0, 10.4.1
 * **Operating system**: Debian Linux, Stretch (9)
 * **Java version**: openjdk 1.8.0_212
 * **Proxy server**: N/A (server startup failure)
 * **Client**: N/A (server startup failure)
 * **Language**: English default

## Additional Information

I hope that support for plaintext LDAP (and other, including DB) passwords in the `airsonic.properties` remains, as this is a useful way to preseed the file via configuration management.

**Comment by joshuaboniface** [comment]
Well disregard me, I was getting this on 10.4.0 as well and just never noticed. I don't think it's actually a problem since LDAP worked fine.

**Comment by joshuaboniface** [comment]
I spoke too soon - this is an issue, and LDAP auth was failing for me until I manually re-saved the manager password in the WebUI.

**Comment by randomnicode** [comment]
It's definitely working with hex: https://github.com/airsonic/airsonic/blob/master/airsonic-main/src/main/java/org/airsonic/player/service/SettingsService.java#L691-L708

However, I'm not sure what the scale effect for changing this would be towards backwards compatibility. If we change this to start using plaintext, everyone's application providing a hex password already would break.

Possible options could be:
(a) just provide password in hex (everyone else is doing it)
(b) try decoding it as hex first and if it fails, just use the plaintext value?
(c) maybe introduce another env variable for plaintext; if no hex is provided it looks at that env variabe for plaintext.

Anyone else have any thoughts?

**Comment by muff1nman** [comment]
I think option (a) is fine. If its really a pain point I vote option (c) where we just have another variable named `LdapManagerPasswordPlaintext`.

**Comment by joshuaboniface** [comment]
I'd still consider this an issue. I'd prefer to be able to seed `airsonic.properties` with these password programmatically from a vault, rather than enter them in the UI. A "plaintext" alternative would be nice if possible. Same applies to the SMTP password.
