### ISSUE TITLE
Lucene Index Not found Exception

### ISSUE THREAD

**Issue by jooola** [airsonic/airsonic#1402]
## Problem description

The logs show an exception about Index not being found. This should not be triggered while the library is still scanning for the index to be created.

### Steps to reproduce

1. Run airsonic 10.5.0
2. Browse to airsonic home page while airsonic is scanning the library for the first time (at least first time for the new lucene index)
3. Check logs

## System information

 * **Airsonic version**: 10.5.0
 * **Operating system**: Debian Buster x64
 * **Java version**: OpenJDK 11

## Additional notes

The logs:
```
2019-11-10 21:21:00.816  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 20750 entries.
2019-11-10 21:21:02.250 ERROR --- o.a.p.s.search.IndexManager              : Failed to initialize SearcherManager.

org.apache.lucene.index.IndexNotFoundException: no segments* file found in MMapDirectory@/opt/airsonic/index16/album lockFactory=org.apache.lucene.store.NativeFSLockFactory@7c6b1ab8: files: [_0.fdt, _0.fdx, write.lock]
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:675) ~[lucene-core-8.2.0.jar!/:8.2.0 31d7ec7bbfdcd2c4cc61d9d35e962165410b65fe - ivera - 2019-07-19 15:05:56]
	at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:84) ~[lucene-core-8.2.0.jar!/:8.2.0 31d7ec7bbfdcd2c4cc61d9d35e962165410b65fe - ivera - 2019-07-19 15:05:56]
	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:76) ~[lucene-core-8.2.0.jar!/:8.2.0 31d7ec7bbfdcd2c4cc61d9d35e962165410b65fe - ivera - 2019-07-19 15:05:56]
	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:64) ~[lucene-core-8.2.0.jar!/:8.2.0 31d7ec7bbfdcd2c4cc61d9d35e962165410b65fe - ivera - 2019-07-19 15:05:56]
	at org.apache.lucene.search.SearcherManager.<init>(SearcherManager.java:125) ~[lucene-core-8.2.0.jar!/:8.2.0 31d7ec7bbfdcd2c4cc61d9d35e962165410b65fe - ivera - 2019-07-19 15:05:56]
	at org.airsonic.player.service.search.IndexManager.getSearcher(IndexManager.java:309) ~[classes!/:10.5.0-RELEASE]
	at org.airsonic.player.service.search.SearchServiceImpl.getRandomAlbums(SearchServiceImpl.java:146) ~[classes!/:10.5.0-RELEASE]
	at org.airsonic.player.controller.HomeController.getRandom(HomeController.java:194) ~[classes!/:10.5.0-RELEASE]
	at org.airsonic.player.controller.HomeController.handleRequestInternal(HomeController.java:99) ~[classes!/:10.5.0-RELEASE]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:854) ~[spring-webmvc-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:765) ~[spring-webmvc-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) ~[spring-webmvc-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[spring-webmvc-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) ~[javax.servlet-api-3.1.0.jar!/:3.1.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar!/:3.1.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.airsonic.player.security.JWTRequestParameterProcessingFilter.doFilter(JWTRequestParameterProcessingFilter.java:62) ~[classes!/:10.5.0-RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.airsonic.player.filter.MetricsFilter.doFilter(MetricsFilter.java:30) ~[classes!/:10.5.0-RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.airsonic.player.filter.ResponseHeaderFilter.doFilter(ResponseHeaderFilter.java:49) ~[classes!/:10.5.0-RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.airsonic.player.filter.RequestEncodingFilter.doFilter(RequestEncodingFilter.java:45) ~[classes!/:10.5.0-RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.airsonic.player.filter.ParameterDecodingFilter.doFilter(ParameterDecodingFilter.java:57) ~[classes!/:10.5.0-RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.airsonic.player.filter.BootstrapVerificationFilter.doFilter(BootstrapVerificationFilter.java:55) ~[classes!/:10.5.0-RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.airsonic.player.security.RESTRequestParameterProcessingFilter.doFilter(RESTRequestParameterProcessingFilter.java:90) ~[classes!/:10.5.0-RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177) ~[spring-security-web-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347) ~[spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263) ~[spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) ~[spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-8.5.43.jar!/:8.5.43]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2019-11-10 21:21:04.213  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 21000 entries.
2019-11-10 21:21:07.704  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 21250 entries.
```

**Comment by tesshucom** [comment]
Is there reproducibility?
At the time of the original PR this case has been confirmed and no exception occurs.

**Comment by fxthomas** [comment]
I can reproduce that on a fresh (Docker) install.

If the library is large enough, Airsonic finishes loading the application before the scan is completed. The exception is then shown on the home page.

**Comment by tesshucom** [comment]
OK.
(It is a case that should be considered, not an edge case. However, replication may take some time.)

I would suggest the following fix if it has to be solved immediately.

https://github.com/airsonic/airsonic/blob/d4a26ed691bf512271fa3ec65e92341cebb3d643/airsonic-main/src/main/java/org/airsonic/player/service/search/IndexManager.java#L307-L316

```
            } catch (IndexNotFoundException e) {
                return null;
            } catch (IOException e) {
                LOG.error("Failed to initialize SearcherManager.", e);
            }
```

Such exception handling is generally not preferred, but it is one of the most effective.
And anyone can understand what are doing.

> This should not be triggered while the library is still scanning for the index to be created.

This suggestion is correct.
However, it may be difficult to realize.
This is because Lucene writes are asynchronous.
The workaround is a little limited.

muff1nman reviews the Searcher implementation very often and made additional implementations too.
Perhaps you will understand immediately and have some opinion.

**Comment by tesshucom** [comment]
OK.
(It is a case that should be considered, not an edge case. However, replication may take some time.)

I would suggest the following fix if it has to be solved immediately.

https://github.com/airsonic/airsonic/blob/d4a26ed691bf512271fa3ec65e92341cebb3d643/airsonic-main/src/main/java/org/airsonic/player/service/search/IndexManager.java#L307-L316

```
            } catch (IndexNotFoundException e) {
                return null;
            } catch (IOException e) {
                LOG.error("Failed to initialize SearcherManager.", e);
            }
```

Such exception handling is generally not preferred, but it is one of the most effective.
And anyone can understand what are doing.

> This should not be triggered while the library is still scanning for the index to be created.

This suggestion is correct.
However, more complex implementation and verification time is required to prove effectiveness.
This is because Lucene writes are asynchronous.

muff1nman reviews the Searcher implementation very often and made additional implementations too.
Perhaps you will understand immediately and have some opinion.

**Comment by tesshucom** [comment]
OK.
(It is a case that should be considered, not an edge case. However, replication may take some time.)

I would suggest the following fix if it has to be solved immediately.

https://github.com/airsonic/airsonic/blob/d4a26ed691bf512271fa3ec65e92341cebb3d643/airsonic-main/src/main/java/org/airsonic/player/service/search/IndexManager.java#L307-L316

```
            } catch (IndexNotFoundException e) {
                return null;
            } catch (IOException e) {
                LOG.error("Failed to initialize SearcherManager.", e);
            }
```

(You may want to output a log.)
Such exception handling is generally not preferred, but it is one of the most effective here.
And anyone can understand what are doing.

> This should not be triggered while the library is still scanning for the index to be created.

This suggestion is correct.
However, more complex implementation and verification time is required to prove effectiveness.
This is because Lucene writes are asynchronous.

muff1nman reviews the Searcher implementation very often and made additional implementations too.
Perhaps you will understand immediately and have some opinion.

**Comment by fxthomas** [comment]
I _think_ that this can be fixed while keeping `IndexManager`'s contract properly.

First, if `IndexNotFoundException` occurs, we can return `null` (which is documented as okay in the method and handled correctly by the rest of Airsonic). It does not fix the underlying issue, but at the very least it will avoid having the same error in the future:

```diff
diff --git a/airsonic-main/src/main/java/org/airsonic/player/service/search/IndexManager.java b/airsonic-main/src/main/java/org/airsonic/player/service/search/IndexManager.java
index 15ce50d5..dd2f7813 100644
--- a/airsonic-main/src/main/java/org/airsonic/player/service/search/IndexManager.java
+++ b/airsonic-main/src/main/java/org/airsonic/player/service/search/IndexManager.java
@@ -306,8 +313,15 @@ public class IndexManager {
             File indexDirectory = getIndexDirectory.apply(indexType);
             try {
                 if (indexDirectory.exists()) {
-                    SearcherManager manager = new SearcherManager(FSDirectory.open(indexDirectory.toPath()), null);
-                    searchers.put(indexType, manager);
+                    SearcherManager manager = null;
+                    try {
+                        manager = new SearcherManager(FSDirectory.open(indexDirectory.toPath()), null);
+                    } catch (IndexNotFoundException e) {
+                        LOG.debug("Index {} does not exist in {}, likely not yet created.", indexType.toString(), indexDirectory.getAbsolutePath());
+                    }
+                    if (!isEmpty(manager)) {
+                        searchers.put(indexType, manager);
+                    }
                 } else {
                     LOG.warn("{} does not exist. Please run a scan.", indexDirectory.getAbsolutePath());
                 }
```

Then, we can create the indices at the same time as the index directory. With this we should be able to guarantee that either a) the index directory doesn't exist or b) the index directory _and_ all the indices exist (aside from very special circumstances such as force-killing the process while the indices are being written, handled by the additional `catch` clause above).

I'm a little unsure about this, but it could work. @tesshucom what do you think?

```diff
diff --git a/airsonic-main/src/main/java/org/airsonic/player/service/search/IndexManager.java b/airsonic-main/src/main/java/org/airsonic/player/service/search/IndexManager.java
index 15ce50d5..312a5387 100644
--- a/airsonic-main/src/main/java/org/airsonic/player/service/search/IndexManager.java
+++ b/airsonic-main/src/main/java/org/airsonic/player/service/search/IndexManager.java
@@ -28,6 +28,7 @@ import org.airsonic.player.service.SettingsService;
 import org.airsonic.player.util.FileUtil;
 import org.airsonic.player.util.Util;
 import org.apache.commons.io.FileUtils;
+import org.apache.commons.lang.time.DateUtils;
 import org.apache.lucene.document.Document;
 import org.apache.lucene.index.*;
 import org.apache.lucene.search.IndexSearcher;
@@ -41,10 +42,7 @@ import org.springframework.stereotype.Component;
 
 import java.io.File;
 import java.io.IOException;
 import java.util.Arrays;
 import java.util.EnumMap;
 import java.util.Map;
 import java.util.Objects;
+import java.util.Date;
+import java.util.Calendar;
 import java.util.function.Function;
 import java.util.function.Supplier;
 import java.util.regex.Pattern;
@@ -404,6 +409,10 @@ public class IndexManager {
         } else {
             if (rootIndexDirectory.get().mkdir()) {
                 LOG.info("Index directory was created (index version {}). ", INDEX_VERSION);
+                MediaLibraryStatistics statistics = new MediaLibraryStatistics(
+                        DateUtils.truncate(new Date(), Calendar.SECOND));
+                startIndexing();
+                stopIndexing(statistics);
             } else {
                 LOG.warn("Failed to create index directory :  (index version {}). ", INDEX_VERSION);
             }
```

**Comment by tesshucom** [comment]
I think the first plan is a quick and realistic one.
The first thing I came up with was that idea.
Comments can include a link to this issue.

I think the second plan is in the dead end.
As a rule of thumb, a file can be used for flags only if the operation is so small that it is not subject to other operations.
It is not a frequently recommended technique.

[CONTRIBUTING](https://github.com/airsonic/airsonic/blob/master/CONTRIBUTING.md) has the following description :
``Limit the scope to the minimum changes necessary to accomplish a discrete and well defined task.``

statistics is just a count cache.
(The contents are different, but the required functions are almost the same as the genre master.)
The same can be done clean with DB record registration, view, on-memory cashe, ehcashe.
It's a lot harder now, but if you need more complexity, you can rethink it more simply.
If it's a burden to start over, it's best to keep the corrections as small as possible.
