### ISSUE TITLE
Airsonic Docker, Ubuntu 18.04, Raspberry Pi 4, Music Collection Gone, Rescanning Failed

### ISSUE THREAD

**Issue by qwertyuser1983** [airsonic/airsonic#1591]
## Problem description

This is a sister issue of https://github.com/linuxserver/docker-airsonic/issues/31

I use Airsonic every day without problems before I stumble to this problem.

My music "catalogue" is gone. The files still there, but for an unknown reason, Airsonic did not want to index them. The statistics on left-hand side in main menu are gone too.

Furthermore, everytime I click on scan media now, the log giving these errors.

```
2020-03-21 18:00:37.201  INFO --- o.a.p.s.MediaScannerService              : Starting to scan media library.
2020-03-21 18:00:38.992  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 3 entries.
2020-03-21 18:00:38.994  INFO --- o.a.p.s.MediaScannerService              : Marking non-present files.
2020-03-21 18:00:39.000  INFO --- o.a.p.s.MediaScannerService              : Marking non-present artists.
2020-03-21 18:00:39.004  INFO --- o.a.p.s.MediaScannerService              : Marking non-present albums.
2020-03-21 18:00:39.057  INFO --- o.a.p.s.MediaScannerService              : Completed media library scan.
2020-03-21 18:00:40.811  INFO --- o.a.p.service.PlaylistService            : Starting playlist import.
2020-03-21 18:00:40.851  WARN --- o.a.p.service.PlaylistService            : Failed to import playlists: java.lang.NullPointerException

java.lang.NullPointerException: null
        at org.airsonic.player.service.PlaylistService.doImportPlaylists(PlaylistService.java:275) ~[classes!/:10.5.0-RELEASE]
        at org.airsonic.player.service.PlaylistService.importPlaylists(PlaylistService.java:257) ~[classes!/:10.5.0-RELEASE]
        at org.airsonic.player.service.MediaScannerService$1.run(MediaScannerService.java:152) [classes!/:10.5.0-RELEASE]

```

### Steps to reproduce

I just don't know, sorry. It happens so suddenly. 

I tried to remove and reinstall Airsonic docker, including removing the image and the server folder, but the problem persists 

## System information

 * **Airsonic version**: *10.5.0-RELEASE – November 7, 20, https://hub.docker.com/r/linuxserver/airsonic*
 * **Operating system**: *Ubuntu 18.04 64 bit from https://github.com/TheRemote/Ubuntu-Server-raspi4-unofficial, on Raspberry Pi 4 - 4 GB*
 * **Java version**: *No idea, sorry*
 * **Proxy server**: *None* 
 * **Client**: *UltraSonic on Nokia 6, Firefox-Snap on Bodhi Linux 16.04 Laptop*
 * **Language**: *English UK*

## Additional notes

My docker compose.yml 
```
version: "2"
services:
  airsonic:
    image: linuxserver/airsonic
    container_name: airsonic
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    volumes:
      - [path1]/AirSonic/Config:/config
      - [path1]/NextCloudPi/Data/nextcloud/data/[user]/files/[path2]/Music:/music
      - [path1]/NextCloudPi/Data/nextcloud/data/[user]/files/[path2]/Renan-Data/Playlists:/playlists
      - [path1]/NextCloudPi/Data/nextcloud/data/[user]/files/[path2]/Podcasts:/podcasts
      - [path1]/NextCloudPi/Data/nextcloud/data/[user]/files/[path2]/Videos:/media
    ports:
      - 4040:4040
    restart: unless-stopped

```
The music and video files persist in my NextCloudPi folder in the same external HDD

The data is safe, so, I need a pointer for "fresh starting" Airsonic. I don't mind solutions involving Airsonic reinstall. 

UPDATE

I find out that Java is indeed running. 
![image](https://user-images.githubusercontent.com/22538918/77226990-f4935800-6bae-11ea-9ca1-6a0835918942.png)

**Comment by qwertyuser1983** [comment]
Using Nefsation help, I find out that the problem is related to HDD permission.

The data is owned by root, so can't be accessed directly.

When the data is copied manually using Nextcloud client, and point my Airsonic to that folder, all working again.

**Comment by qwertyuser1983** [comment]
Naah, I spoke too soon.

The same problem returns after this morning restart.

**Comment by fxthomas** [comment]
Can you check one thing : when you stop Airsonic, is the database cleanly stopped? Is there a `airsonic.lck` file in the `db` folder?

Supposedly the big upgrade to HSQLDB 2.5 (#1345, which I intend to merge soon) will fix a lot of issues with HSQLDB 1.8. I certainly haven't had any database issues since I've upgraded my own instance to it.

I'll leave this open until we do a release with that version.

**Comment by fxthomas** [comment]
Ah, also, it sounds like you may have an invalid playlist file? Can you try removing everything in the "playlists" folder and try again?
