### ISSUE TITLE
java.lang.UnsupportedOperationException: Not implemented for this format

### ISSUE THREAD

**Issue by HolyMacarony** [airsonic/airsonic#1625]
## Problem description
**Thank you all for this great project, it worked great so far!
So i started the latest version 10.6.0 today and the library scan fails at about 26500/~86000 files with the following stack trace:**

```
2020-04-17 02:35:12.332  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 26500 entries.
2020-04-17 02:35:14.694 ERROR --- o.a.p.s.MediaScannerService              : Failed to scan media library.

java.lang.UnsupportedOperationException: Not implemented for this format
        at org.jaudiotagger.audio.generic.GenericTag.getValue(GenericTag.java:191) ~[jaudiotagger-2.2.5.jar!/:na]
        at org.jaudiotagger.tag.wav.WavTag.getValue(WavTag.java:242) ~[jaudiotagger-2.2.5.jar!/:na]
        at org.jaudiotagger.tag.wav.WavTag.getFirst(WavTag.java:247) ~[jaudiotagger-2.2.5.jar!/:na]
        at org.airsonic.player.service.metadata.JaudiotaggerParser.getTagField(JaudiotaggerParser.java:128) ~[classes!/:10.6.0-RELEASE]
        at org.airsonic.player.service.metadata.JaudiotaggerParser.getRawMetaData(JaudiotaggerParser.java:99) ~[classes!/:10.6.0-RELEASE]
        at org.airsonic.player.service.metadata.MetaDataParser.getMetaData(MetaDataParser.java:47) ~[classes!/:10.6.0-RELEASE]
        at org.airsonic.player.service.MediaFileService.createMediaFile(MediaFileService.java:537) ~[classes!/:10.6.0-RELEASE]
        at org.airsonic.player.service.MediaFileService.updateChildren(MediaFileService.java:397) ~[classes!/:10.6.0-RELEASE]
        at org.airsonic.player.service.MediaFileService.getChildrenOf(MediaFileService.java:193) ~[classes!/:10.6.0-RELEASE]
        at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:240) [classes!/:10.6.0-RELEASE]
        at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:244) [classes!/:10.6.0-RELEASE]
        at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:244) [classes!/:10.6.0-RELEASE]
        at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:244) [classes!/:10.6.0-RELEASE]
        at org.airsonic.player.service.MediaScannerService.doScanLibrary(MediaScannerService.java:183) [classes!/:10.6.0-RELEASE]
        at org.airsonic.player.service.MediaScannerService.access$000(MediaScannerService.java:50) [classes!/:10.6.0-RELEASE]
        at org.airsonic.player.service.MediaScannerService$1.run(MediaScannerService.java:151) [classes!/:10.6.0-RELEASE]

```
**I just verified that the same files are no problem to the previous version 10.5.0-RELEASE – 7. November 2019, nothing else changed:**

```
2020-04-17 03:15:40.061  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 26500 entries.
2020-04-17 03:15:50.346  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 26750 entries.
2020-04-17 03:16:04.361  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 27000 entries.
2020-04-17 03:16:17.349  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 27250 entries.
2020-04-17 03:16:30.668  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 27500 entries.
2020-04-17 03:16:43.321  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 27750 entries.
2020-04-17 03:17:00.658  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 28000 entries.
2020-04-17 03:17:17.613  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 28250 entries.
2020-04-17 03:17:47.482  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 28500 entries.
2020-04-17 03:17:59.656  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 28750 entries.
2020-04-17 03:18:13.374  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 29000 entries.

```

### Steps to reproduce

just use the latest airsonic version instead of previous and scan files again

## System information

 * **Airsonic version**: *10.6.0-RELEASE – 15. April 2020*
 * **Operating system**: *Linux Dietpi 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux on Raspberry pi 4B*
 * **Java version**: *Apache Tomcat/8.5.51, java 1.8.0_212, Linux (115,5 MB / 152,6 MB)*
 * **Proxy server**:  None
 * **Client**: *default WebApp*
 * **Language**: *Deutsch*

## Additional notes

*The previous version worked for several months with this very files. Is there a way to find the exact file that causes this error? Maybe a more verbose loglevel for the exception stacktrace or how can i find out the faulty file to tell you more about it?*

**Comment by tesshucom** [comment]
Possibility of degrading by https://github.com/airsonic/airsonic/commit/c6eed14db5a91bb0f384f53189d058c6d8866633#diff-88dc2e86f487f6d9ee12b60ab19d44b5 ?
It seems that the point I was wondering about had already been pointed out.
It is necessary to consider the patch version for the content of the failure.

**Comment by tesshucom** [comment]
Possibility of degrading by https://github.com/airsonic/airsonic/commit/c6eed14db5a91bb0f384f53189d058c6d8866633#diff-88dc2e86f487f6d9ee12b60ab19d44b5 ?
(I'm still not sure if this is direct, as exception rewriting also exists in other revisions.)

It seems that the point I was wondering about had already been pointed out.
It is necessary to consider the patch version for the content of the failure.

**Comment by tesshucom** [comment]
There is exactly what you are looking for.

Possibility of degrading by https://github.com/airsonic/airsonic/commit/c6eed14db5a91bb0f384f53189d058c6d8866633#diff-88dc2e86f487f6d9ee12b60ab19d44b5 ?
(I'm still not sure if this is direct, as exception rewriting also exists in other revisions.)



It seems that the point I was wondering about had already been pointed out.
It is necessary to consider the patch version for the content of the failure.

**Comment by randomnicode** [comment]
No, this is the offending commit: https://github.com/airsonic/airsonic/commit/a13552b6f55520fb7bb544576c2028326fd0acfd#diff-88dc2e86f487f6d9ee12b60ab19d44b5R129

The exception was getting caught earlier, but the catch was narrowed to "KeyNotFoundException", which allows the offending error to escape now and bubble up.
Broadening the catch again to catch the unchecked exception should work. (KeyNotFoundException -> Exception)
Additionally there should be try-catches around individual files so one file doesn't ruin the entire scan.
And lastly, @HolyMacarony is right that the file throwing exceptions should be logged so at least we know what's causing problems. In this case, the matter seems obvious that it's trying to grab a disc number from a WAV header, which obviously doesn't exist, but in other scenarios it may not be so obvious.

**Comment by tesshucom** [comment]
Oh it's ok.

I think it makes sense to revert all exceptions compared to the previous revision.
How about?

There are many unexpected tag patterns (Including file corruption).
That's the reason for runtime.

**Comment by fxthomas** [comment]
Thanks for looking into this! This'll probably need a specific test case, but for now reverting things sounds like the right decision!

**Comment by tesshucom** [comment]
There is also the aspect of returning to a time when there was no problem.
However, if the code is written by the designer under the policy of "not being too dependent on the exception structure of a specific product", the answer may be good.
If we modify this, we break the principle and become more dependent.
