### ISSUE TITLE
Metadata scan: "Unable to find next atom because identifier is invalid"

### ISSUE THREAD

**Issue by richardmayer** [airsonic/airsonic#1671]
## Problem description

Hello,
on my Airsonic seem to have problems reading the metadata of very very few of my files, which I do not understand, beacause they are being generated exactly the same way.
I do rip the files myself with ExactAudioCopy and the are encoded to AppleLossless with iTunes.
Metadata is also edited via iTunes.

Exporting the metadata with ffmpeg, I cannot see any problem with the metadata.
So I do not understand, why Airsonic cannot scan the following file.
Here's the error message in the Log:

```shell
2020-04-28 07:01:11.697  WARN --- o.a.p.s.m.JaudiotaggerParser             : Error when parsing tags in /mnt/storage/airsonic/eac_lossless/Shaken and Stirred (EAC Lossless)/04 All Time High feat. Pulp.m4a

org.jaudiotagger.audio.exceptions.CannotReadException: /mnt/storage/airsonic/eac_lossless/Shaken and Stirred (EAC Lossless)/04 All Time High feat. Pulp.m4a:Unable to find next atom because identifier is invalid Îïy
	at org.jaudiotagger.audio.generic.AudioFileReader.read(AudioFileReader.java:117) ~[jaudiotagger-2.2.5.jar!/:na]
	at org.jaudiotagger.audio.AudioFileIO.readFile(AudioFileIO.java:355) ~[jaudiotagger-2.2.5.jar!/:na]
	at org.jaudiotagger.audio.AudioFileIO.read(AudioFileIO.java:198) ~[jaudiotagger-2.2.5.jar!/:na]
	at org.airsonic.player.service.metadata.JaudiotaggerParser.getRawMetaData(JaudiotaggerParser.java:87) ~[classes!/:10.6.1-RELEASE]
	at org.airsonic.player.service.metadata.MetaDataParser.getMetaData(MetaDataParser.java:47) [classes!/:10.6.1-RELEASE]
	at org.airsonic.player.service.MediaFileService.createMediaFile(MediaFileService.java:496) [classes!/:10.6.1-RELEASE]
	at org.airsonic.player.service.MediaFileService.updateChildren(MediaFileService.java:397) [classes!/:10.6.1-RELEASE]
	at org.airsonic.player.service.MediaFileService.getChildrenOf(MediaFileService.java:193) [classes!/:10.6.1-RELEASE]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:240) [classes!/:10.6.1-RELEASE]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:244) [classes!/:10.6.1-RELEASE]
	at org.airsonic.player.service.MediaScannerService.doScanLibrary(MediaScannerService.java:183) [classes!/:10.6.1-RELEASE]
	at org.airsonic.player.service.MediaScannerService.access$000(MediaScannerService.java:50) [classes!/:10.6.1-RELEASE]
	at org.airsonic.player.service.MediaScannerService$1.run(MediaScannerService.java:151) [classes!/:10.6.1-RELEASE]
Caused by: org.jaudiotagger.audio.exceptions.InvalidBoxHeaderException: Unable to find next atom because identifier is invalid Îïy
	at org.jaudiotagger.audio.mp4.atom.Mp4BoxHeader.update(Mp4BoxHeader.java:158) ~[jaudiotagger-2.2.5.jar!/:na]
	at org.jaudiotagger.audio.mp4.Mp4AtomTree.buildTree(Mp4AtomTree.java:120) ~[jaudiotagger-2.2.5.jar!/:na]
	at org.jaudiotagger.audio.mp4.Mp4AtomTree.<init>(Mp4AtomTree.java:83) ~[jaudiotagger-2.2.5.jar!/:na]
	at org.jaudiotagger.audio.mp4.Mp4InfoReader.read(Mp4InfoReader.java:350) ~[jaudiotagger-2.2.5.jar!/:na]
	at org.jaudiotagger.audio.mp4.Mp4FileReader.getEncodingInfo(Mp4FileReader.java:41) ~[jaudiotagger-2.2.5.jar!/:na]
	at org.jaudiotagger.audio.generic.AudioFileReader.read(AudioFileReader.java:104) ~[jaudiotagger-2.2.5.jar!/:na]
	... 12 common frames omitted
```

This is the metadata from the problem-file:
```
;FFMETADATA1
major_brand=M4A 
minor_version=0
compatible_brands=M4A mp42isom
date=1999
title=All Time High feat. Pulp
compilation=0
gapless_playback=0
genre=Soundtrack
Encoding Params=vers
iTunNORM= 00000C41 00000CA1 00008ABB 0000910D 0001F280 0003AA98 000075B1 000075C5 0003404A 0003D7AC
disc=1/1
comment=EAC Lossless
artist=David Arnold
track=4/11
album=Shaken and Stirred (EAC Lossless)
encoder=Lavf57.56.101
```

And here's the next track from the same album, working fine:
```
;FFMETADATA1
major_brand=M4A 
minor_version=0
compatible_brands=M4A mp42isom
date=1999
title=Moonraker feat. Shara Nelson
compilation=0
gapless_playback=0
genre=Soundtrack
Encoding Params=vers
iTunNORM= 000004A7 000004AC 000038AF 00003844 0002E369 0002E57E 00006DD8 00006FA6 0002E33A 0002CED1
disc=1/1
comment=EAC Lossless
artist=David Arnold
track=5/11
album=Shaken and Stirred (EAC Lossless)
encoder=Lavf57.56.101
```

Any ideas, what else I might try out?

### Steps to reproduce

Import Album into the Airsonic-Storage and rescan library.

## System information

 * **Airsonic version**: 10.6.1-RELEASE – 19. April 2020
 * **Operating system**: cat /etc/debian_version 9.12 Linux macdeb 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux
 * **Java version**:  openjdk version "1.8.0_242"
 * **Proxy server**:  None
 * **Client**: Safari, play:Sub
 * **Language**: German

## Additional notes

*Include any extra notes here. Otherwise you may remove this section.*

**Comment by dontoverthinkit** [comment]
Assume that request for feedback has gone direct to the OP @tesshucom?
This is the first post I hit when googling for the error message "Unable to find next atom because identifier is invalid"
I realise I am probably a weird edge case - possibly even unsupported - but I am receiving the errors on .m4b files which look 
like it is being thrown in the same area. Happy to raise a seperate issue, or provide additional detail against this one (to save duplication) - do you have a preference?

Caused by: org.jaudiotagger.audio.exceptions.NullBoxIdException: Unable to find next atom because identifier is invalid
at org.jaudiotagger.audio.mp4.atom.Mp4BoxHeader.update(Mp4BoxHeader.java:153) ~[jaudiotagger-2.2.5.jar!/:na]
at org.jaudiotagger.audio.mp4.atom.Mp4BoxHeader.seekWithinLevel(Mp4BoxHeader.java:273) ~[jaudiotagger-2.2.5.jar!/:na]
at org.jaudiotagger.audio.mp4.Mp4InfoReader.read(Mp4InfoReader.java:93) ~[jaudiotagger-2.2.5.jar!/:na]
at org.jaudiotagger.audio.mp4.Mp4FileReader.getEncodingInfo(Mp4FileReader.java:41) ~[jaudiotagger-2.2.5.jar!/:na]
at org.jaudiotagger.audio.generic.AudioFileReader.read(AudioFileReader.java:104) ~[jaudiotagger-2.2.5.jar!/:na]


Kind regards,
Del
