### ISSUE TITLE
Crash when updgrading from 1.6.1 to 1.6.2 (

### ISSUE THREAD

**Issue by Linuxine** [airsonic/airsonic#1712]
Hi,

I have tried to upgrade my Airsonic installation on Centos 7 (java version : java version "1.8.0_101") from 1.6.1 to 1.6.2. There seems to be an issue with my db (I use the default H2 database), since I get the following error on startup:

```
May 14 14:27:31  java[17612]: 2020-05-14 14:27:31.237 ERROR --- o.a.p.spring.SpringLiquibase             : ===============================================
May 14 14:27:31  java[17612]: 2020-05-14 14:27:31.237 ERROR --- o.a.p.spring.SpringLiquibase             : An exception occurred during database migration
May 14 14:27:31  java[17612]: 2020-05-14 14:27:31.237 ERROR --- o.a.p.spring.SpringLiquibase             : A rollback file has been generated at /var/airsonic/rollback.sql
May 14 14:27:31  java[17612]: 2020-05-14 14:27:31.237 ERROR --- o.a.p.spring.SpringLiquibase             : Execute it within your database to rollback any changes
May 14 14:27:31  java[17612]: 2020-05-14 14:27:31.247 ERROR --- o.a.p.spring.SpringLiquibase             : The exception is as follows
May 14 14:27:31  java[17612]: liquibase.exception.DatabaseException: java.sql.SQLException: error in script file line: 5948 java.io.IOException: org.hsqldb.HsqlException: Value too long
May 14 14:27:31  java[17612]: at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:316) ~[liquibase-core-3.8.7.jar!/:na]
May 14 14:27:31  java[17612]: at org.airsonic.player.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:25) ~[classes!/:10.6.2-RELEASE]
```

The stack trace is very long, let me know if you need more details. I did not find which line was containing a value too long, the error is not explicit enough for me... I managed to start the application again by renaming my "db" folder, to start anew, which is quick since I only have one user and one music folder. So this is not a big issue for me, but maybe it will happen to others when migrating ?
Regards,

**Comment by randomnicode** [comment]
Confused.

>(I use the default H2 database)

The default isn't H2, it's HSQLDB

> org.hsqldb.HsqlException: Value too long

indicates your system is trying to use HSQLDB

And yet, we don't use 1.6.1 of HSQLDB. We use at least 1.8.x?

Maybe you meant to say Airsonic 10.6.2 (with HSQLDB 1.8.x)? and not H2 1.6.2?

**Comment by fxthomas** [comment]
Can you look at `db/airsonic.script` line 5948 and post the contents?

-----

Also, guesswork follows:

Might be related to #1440 ? I don't think the upgrade is related (nothing changed in the db between 10.6.1 and 10.6.2), the issue just appeared simultaneously with it by "chance".

My hunch following #1440 is that old HSQLDB versions used to do some really weird stuff with some database types (including those that we had back in https://github.com/airsonic/airsonic/pull/876#issuecomment-534762686 when testing the 2.5.0 migration), and that it sometimes appear like this.

**Comment by Linuxine** [comment]
Hi,

sorry for the mistakes about the version (I forgot a 0, indeed !) and the database. 

Actually, @fxthomas my airsonic.script only contains 3718 lines, so I guess the error was referring to another file ? I was indeed surprised to have such an error on a minor version upgrade, that is why I opened the ticket, in case this was a real issue. Unfortunately, everything is quite old on CentOS 7, so my version of HSQLDB might be old, indeed :/
