### ISSUE TITLE
tomcat 10.6.2 war install problems

### ISSUE THREAD

**Issue by pacija** [airsonic/airsonic#1715]
Hi,

I have been upgrading at least five airsonic versions without any hassle by putting new airsonic.war into tomcat's webapps folder and restarting tomcat.

When I put 10.6.2 airsonic.war into tomcat's webapps folder and restart tomcat, airsonic GUI still shows 10.6.1 and informs me about new version available.

Environment:
FreeBSD 12.1-RELEASE-p3 x64
tomcat9-9.0.34
openjdk8-8.252.09.1

I see the following in my catalina.2020-05-16.log:
```
16-May-2020 11:32:15.996 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/apache-tomcat-9.0/webapps/airsonic.war]
16-May-2020 11:32:22.526 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
16-May-2020 11:32:40.985 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/apache-tomcat-9.0/webapps/airsonic.war] has finished in [24,989] ms
```
From airsonic.log:
```
2020-05-16 11:32:24.515  INFO --- org.airsonic.player.Application          : Starting Application on neela.underbottom.org with PID 41371 (/usr/local/apache-tomcat-9.0/webapps/airsonic/WEB-INF/classes started by root in /)
2020-05-16 11:32:24.518  INFO --- org.airsonic.player.Application          : The following profiles are active: legacy
2020-05-16 11:32:29.793  INFO --- l.executor.jvm.JdbcExecutor              : SELECT COUNT(*) FROM DATABASECHANGELOGLOCK
2020-05-16 11:32:29.805  INFO --- l.executor.jvm.JdbcExecutor              : SELECT COUNT(*) FROM DATABASECHANGELOGLOCK
2020-05-16 11:32:29.823  INFO --- l.l.StandardLockService                  : Successfully acquired change log lock
2020-05-16 11:32:32.225  INFO --- l.executor.jvm.JdbcExecutor              : SELECT MD5SUM FROM DATABASECHANGELOG WHERE MD5SUM IS NOT NULL
2020-05-16 11:32:32.228  INFO --- l.executor.jvm.JdbcExecutor              : SELECT COUNT(*) FROM DATABASECHANGELOG
2020-05-16 11:32:32.229  INFO --- l.c.StandardChangeLogHistoryService      : Reading from DATABASECHANGELOG
2020-05-16 11:32:32.230  INFO --- l.executor.jvm.JdbcExecutor              : SELECT * FROM DATABASECHANGELOG ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2020-05-16 11:32:32.431  INFO --- l.l.StandardLockService                  : Successfully released change log lock
2020-05-16 11:32:32.433  INFO --- l.executor.jvm.JdbcExecutor              : SELECT COUNT(*) FROM DATABASECHANGELOGLOCK
2020-05-16 11:32:32.434  INFO --- l.executor.jvm.JdbcExecutor              : SELECT COUNT(*) FROM DATABASECHANGELOGLOCK
2020-05-16 11:32:32.435  INFO --- l.executor.jvm.JdbcExecutor              : SELECT LOCKED FROM DATABASECHANGELOGLOCK WHERE ID=1
2020-05-16 11:32:32.439  INFO --- l.l.StandardLockService                  : Successfully acquired change log lock
2020-05-16 11:32:32.455  INFO --- l.executor.jvm.JdbcExecutor              : SELECT MD5SUM FROM DATABASECHANGELOG WHERE MD5SUM IS NOT NULL
2020-05-16 11:32:32.457  INFO --- l.executor.jvm.JdbcExecutor              : SELECT COUNT(*) FROM DATABASECHANGELOG
2020-05-16 11:32:32.457  INFO --- l.c.StandardChangeLogHistoryService      : Reading from DATABASECHANGELOG
2020-05-16 11:32:32.457  INFO --- l.executor.jvm.JdbcExecutor              : SELECT * FROM DATABASECHANGELOG ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2020-05-16 11:32:32.472  INFO --- l.l.StandardLockService                  : Successfully released change log lock
2020-05-16 11:32:32.643  INFO --- o.a.p.service.SettingsService            : Java: 1.8.0_252, OS: FreeBSD
2020-05-16 11:32:36.059  INFO --- o.airsonic.player.dao.PlayerDao          : Deleted 2 player(s) that haven't been used after Tue Mar 17 11:32:36 CET 2020
2020-05-16 11:32:36.156  INFO --- o.a.p.s.search.IndexManager              : Index was found (index version 18).
2020-05-16 11:32:36.160  INFO --- o.a.p.s.MediaScannerService              : Automatic media library scanning scheduled to run every 1 day(s), starting at 2020-05-17T03:00:00.159
2020-05-16 11:32:36.812  INFO --- o.a.p.service.PodcastService             : Automatic Podcast update scheduled to run every 24 hour(s), starting at Sat May 16 11:37:36 CEST 2020
2020-05-16 11:32:38.891  INFO --- org.airsonic.player.Application          : Detected Tomcat web server
2020-05-16 11:32:40.555  INFO --- org.airsonic.player.Application          : Started Application in 17.718 seconds (JVM running for 25.441)
2020-05-16 11:32:41.662  INFO --- o.a.p.f.BootstrapVerificationFilter      : Servlet container: Apache Tomcat/9.0.34
2020-05-16 11:34:42.039  INFO --- o.airsonic.player.dao.PlayerDao          : Created player 116.
2020-05-16 11:34:42.068  INFO --- o.a.p.service.VersionService             : Resolved local Airsonic version to: 10.6.1-RELEASE
2020-05-16 11:37:36.831  INFO --- o.a.p.service.PodcastService             : Starting scheduled Podcast refresh.
2020-05-16 11:37:36.832  INFO --- o.a.p.service.PodcastService             : Completed scheduled Podcast refresh.
```
Any ideas what can I do to successfully upgrade?

Thank you in advance.

**Comment by pacija** [comment]
I have also noticed some warnings about airsonic in tomcat log. Perhaps they are related to inability to upgrade?

```
22-May-2020 12:35:37.060 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [airsonic] registered the JDBC driver [org.hsqldb.jdbcDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
22-May-2020 12:35:37.061 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [airsonic] appears to have started a thread named [HSQLDB Timer @5a00c334] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 org.hsqldb.lib.HsqlTimer.nextTask(Unknown Source)
 org.hsqldb.lib.HsqlTimer$TaskRunner.run(Unknown Source)
 java.lang.Thread.run(Thread.java:748)
22-May-2020 12:35:37.061 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [airsonic] appears to have started a thread named [pool-1-thread-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)
22-May-2020 12:35:37.061 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [airsonic] appears to have started a thread named [pool-2-thread-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)
22-May-2020 12:35:37.080 INFO [main] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["http-nio-127.0.2.133-8080"]
22-May-2020 12:35:37.081 INFO [main] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["ajp-nio-127.0.2.133-8009"]
22-May-2020 12:35:37.084 INFO [main] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["http-nio-127.0.2.133-8080"]
22-May-2020 12:35:37.084 INFO [main] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["ajp-nio-127.0.2.133-8009"]
Exception in thread "Thread-9" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: java/util/function/UnaryOperator
        at org.airsonic.player.service.UPnPService.ensureServiceStopped(UPnPService.java:97)
        at org.airsonic.player.service.UPnPService.lambda$init$0(UPnPService.java:82)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: java/util/function/UnaryOperator
        ... 3 more
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [java.util.function.UnaryOperator]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1375)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1226)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)
        ... 3 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [java.util.function.UnaryOperator]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1385)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1373)
        ... 5 more
```

**Comment by tesshucom** [comment]
> I have also noticed some warnings about airsonic in tomcat log. Perhaps they are related to inability to upgrade?

Probably.

Seems to be a deployment issue. Have you tried deleting the unzipped airsonic directory in webapps?

**Comment by pacija** [comment]
> Have you tried deleting the unzipped airsonic directory in webapps?

After deleting unzipped airsonic directory in webapps (which was 10.6.1), 10.6.2 installed successfully.

My upgrade problem is solved, but I am still concerned about warnings about possible memory leaks related to inability to unregister JDBC driver and stop HSQLDB Timer, pool-1-thread-1 and pool-2-thread-1 threads:
```
24-May-2020 18:14:22.992 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [airsonic] registered the JDBC driver [org.hsqldb.jdbcDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
24-May-2020 18:14:22.993 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [airsonic] appears to have started a thread named [HSQLDB Timer @27673a67] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 org.hsqldb.lib.HsqlTimer.nextTask(Unknown Source)
 org.hsqldb.lib.HsqlTimer$TaskRunner.run(Unknown Source)
 java.lang.Thread.run(Thread.java:748)
24-May-2020 18:14:22.994 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [airsonic] appears to have started a thread named [pool-1-thread-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)
24-May-2020 18:14:22.994 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [airsonic] appears to have started a thread named [pool-2-thread-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)
```
Should I close this issue and open another one about possible memory leaks?

**Comment by tesshucom** [comment]
If you do not mind.
It's a problem that has to be tracked...
