### ISSUE TITLE
airsonic doesn't want to start !!!

### ISSUE THREAD

**Issue by jajaX** [airsonic/airsonic#1775]
## Problem description

Hi, (sorry for my bad english !)
my airsonic doesn't want to start and I want to solve that !!!

apache2 => works
tomcat9 => works
java => works (I think)

I have already installed soff but no access message since few days. I want install again but it doesn't want to start.

I use Stand-alone WAR installation.
I put the soft in /var/airsonic folder and start it (for test) =>

```
/var/www/airsonic$ java -jar airsonic.war
           _                       _          
     /\   (_)                     (_)         
    /  \   _ _ __  ___  ___  _ __  _  ___     
   / /\ \ | | '__|/ __|/ _ \| '_ \| |/ __|    
  / ____ \| | |   \__ \ (_) | | | | | (__     
 /_/    \_\_|_|   |___/\___/|_| |_|_|\___|    
                                               
                        10.6.2-RELEASE



2020-07-21 01:20:55.818 ERROR --- o.s.boot.SpringApplication               : Application startup failed

java.lang.RuntimeException: Could not create new property file
        at org.airsonic.player.service.ApacheCommonsConfigurationService.<init>(ApacheCommonsConfigurationService.java:35) ~[classes!/:10.6.2-RELEASE]
        at org.airsonic.player.spring.CustomPropertySourceConfigurer.initialize(CustomPropertySourceConfigurer.java:20) ~[classes!/:10.6.2-RELEASE]
        at org.airsonic.player.spring.CustomPropertySourceConfigurer.initialize(CustomPropertySourceConfigurer.java:13) ~[classes!/:10.6.2-RELEASE]
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:545) ~[spring-boot-1.5.22.RELEASE.jar!/:1.5.22.RELEASE]
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:332) ~[spring-boot-1.5.22.RELEASE.jar!/:1.5.22.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:299) ~[spring-boot-1.5.22.RELEASE.jar!/:1.5.22.RELEASE]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:135) ~[spring-boot-1.5.22.RELEASE.jar!/:1.5.22.RELEASE]
        at org.airsonic.player.Application.main(Application.java:207) ~[classes!/:10.6.2-RELEASE]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[airsonic.war:10.6.2-RELEASE]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[airsonic.war:10.6.2-RELEASE]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) ~[airsonic.war:10.6.2-RELEASE]
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) ~[airsonic.war:10.6.2-RELEASE]
Caused by: java.io.FileNotFoundException: /var/airsonic/airsonic.properties (Permission non accordée)
        at java.base/java.io.FileOutputStream.open0(Native Method) ~[na:na]
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298) ~[na:na]
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237) ~[na:na]
        at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:365) ~[commons-io-2.6.jar!/:2.6]
        at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:324) ~[commons-io-2.6.jar!/:2.6]
        at org.apache.commons.io.FileUtils.touch(FileUtils.java:440) ~[commons-io-2.6.jar!/:2.6]
        at org.airsonic.player.service.ApacheCommonsConfigurationService.<init>(ApacheCommonsConfigurationService.java:33) ~[classes!/:10.6.2-RELEASE]
        ... 15 common frames omitted
```
here my arisonic.service :: 

`[Unit]
Description=Airsonic Media Server
After=remote-fs.target network.target
AssertPathExists=/var/airsonic

[Service]
Type=simple
Environment="JAVA_JAR=/var/airsonic/airsonic.war"
Environment="JAVA_OPTS=-Xmx700m"
Environment="AIRSONIC_HOME=/var/airsonic"
Environment="PORT=4050"
Environment="CONTEXT_PATH=/airsonic"
Environment="JAVA_ARGS="
EnvironmentFile=-/etc/sysconfig/airsonic
ExecStart=/usr/bin/java \
          $JAVA_OPTS \
          -Dairsonic.home=${AIRSONIC_HOME} \
          -Dserver.servlet.contextPath=${CONTEXT_PATH} \
          -Dserver.port=${PORT} \
          -jar ${JAVA_JAR} $JAVA_ARGS
User=airsonic
Group=airsonic

# See https://www.freedesktop.org/software/systemd/man/systemd.exec.html
# for details
DevicePolicy=closed
DeviceAllow=char-alsa rw
NoNewPrivileges=yes
PrivateTmp=yes
PrivateUsers=yes
ProtectControlGroups=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
RestrictNamespaces=yes
RestrictRealtime=yes
SystemCallFilter=~@clock @debug @module @mount @obsolete @privileged @reboot @setuid @swap
ReadWritePaths=/var/airsonic

# You can uncomment the following line if you're not using the jukebox
# This will prevent airsonic from accessing any real (physical) devices
#PrivateDevices=yes

# You can change the following line to `strict` instead of `full`
# if you don't want airsonic to be able to
# write anything on your filesystem outside of AIRSONIC_HOME.
ProtectSystem=full

# You can uncomment the following line if you don't have any media
# in /home/…. This will prevent airsonic from ever reading/writing anything there.
#ProtectHome=true

# You can uncomment the following line if you're not using the OpenJDK.
# This will prevent processes from having a memory zone that is both writeable
# and executeable, making hacker's lifes a bit harder.
#MemoryDenyWriteExecute=yes

[Install]
WantedBy=multi-user.target

`
I use 4050 port.

here my airsonic (in /etc/default) :

`# Set the location of the standalone war to use
#JAVA_JAR=/var/airsonic/airsonic.war

# Set any java opts separated by spaces
#JAVA_OPTS=-Xmx700m

# Set a different location for airsonic home. 
# If this path is /var/libresonic or even contains "libresonic",
# the data from a previous libresonic can be used as is (i.e. without
# renaming libresonic.properties,db/libresonic*,etc
#AIRSONIC_HOME=/var/airsonic

# Change the port to listen on
PORT=4050

# Change the path that is listened on
#CONTEXT_PATH=/airsonic

# Add any java args. These are different than JAVA_OPTS in that 
# they are passed directly to the program. The default is empty:
#JAVA_ARGS=

# Note that there are several settings for spring boot, not explicitly listed
# here, but can be used in either JAVA_OPTS or JAVA_ARGS. The full list
# can be found here: 
# https://docs.spring.io/spring-boot/docs/1.4.5.RELEASE/reference/htmlsingle/#common-application-properties
# For example to set debug across the board:
#JAVA_ARGS=--debug

# Or to change the ip address that is listened on:
#JAVA_ARGS=--server.address=127.0.0.1
`

### Steps to reproduce

I don't, I haven't got no access after few days...

## System information

 * **Airsonic version**: latest
 * **Operating system**: kubuntu 20.04.
  * **Java version**: openjdk version "11.0.7
 * **Proxy server**:  None
 * **Client**: *what browser and version you use to access the Airsonic web
   interface, or the name and version of another app you're using.*
 * **Language**: *which langauge/internationalization is in use*

## Additional notes

*Include any extra notes here. Otherwise you may remove this section.*

**Comment by jajaX** [comment]
I found the problem !!!

I put my folder in /var/www/airsonic
the system want lauch the program to /var/airsonic !
