### ISSUE TITLE
java.lang.RuntimeException: Could not create new property file

### ISSUE THREAD

**Issue by c0d3x7** [airsonic/airsonic#1791]
## Problem description

can't access localhost:4040

### Steps to reproduce

*Describe how somebody else could observe the same behavior you do. If possible,
include relevant configuration or files that cause the problem. If sharing media
files, ensure you are legally permitted to share copies!*

1. follow installation steps for windows 10
2. launch airsonic.cmd
3. windows powershell give this error: 2020-09-01 12:38:31.003 ERROR --- o.s.boot.SpringApplication               : Application startup failed

## System information

Airsonic version10.6.2
windows 10 entreprise ltsc
 Java version 1.8.0_261

this is what the powershell shows after i launch airsonic

PS C:\Program Files\Airsonic> .\airsonic.cmd

C:\Program Files\Airsonic>java.exe -Dairsonic.home="C:\\Program Files\\Airsonic" -Dserver.port=4040 -jar airsonic.war
           _                       _
     /\   (_)                     (_)
    /  \   _ _ __  ___  ___  _ __  _  ___
   / /\ \ | | '__|/ __|/ _ \| '_ \| |/ __|
  / ____ \| | |   \__ \ (_) | | | | | (__
 /_/    \_\_|_|   |___/\___/|_| |_|_|\___|

                        10.6.2-RELEASE

2020-09-01 12:38:31.003 ERROR --- o.s.boot.SpringApplication               : Application startup failed

java.lang.RuntimeException: Could not create new property file
        at org.airsonic.player.service.ApacheCommonsConfigurationService.<init>(ApacheCommonsConfigurationService.java:35) ~[classes!/:10.6.2-RELEASE]
        at org.airsonic.player.spring.CustomPropertySourceConfigurer.initialize(CustomPropertySourceConfigurer.java:20) ~[classes!/:10.6.2-RELEASE]
        at org.airsonic.player.spring.CustomPropertySourceConfigurer.initialize(CustomPropertySourceConfigurer.java:13) ~[classes!/:10.6.2-RELEASE]
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:545) ~[spring-boot-1.5.22.RELEASE.jar!/:1.5.22.RELEASE]
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:332) ~[spring-boot-1.5.22.RELEASE.jar!/:1.5.22.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:299) ~[spring-boot-1.5.22.RELEASE.jar!/:1.5.22.RELEASE]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:135) [spring-boot-1.5.22.RELEASE.jar!/:1.5.22.RELEASE]
        at org.airsonic.player.Application.main(Application.java:207) [classes!/:10.6.2-RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_261]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_261]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_261]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_261]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [airsonic.war:10.6.2-RELEASE]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [airsonic.war:10.6.2-RELEASE]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [airsonic.war:10.6.2-RELEASE]
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) [airsonic.war:10.6.2-RELEASE]
Caused by: java.io.FileNotFoundException: C:\Program Files\Airsonic\airsonic.properties (Access is denied)
        at java.io.FileOutputStream.open0(Native Method) ~[na:1.8.0_261]
        at java.io.FileOutputStream.open(Unknown Source) ~[na:1.8.0_261]
        at java.io.FileOutputStream.<init>(Unknown Source) ~[na:1.8.0_261]
        at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:365) ~[commons-io-2.6.jar!/:2.6]
        at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:324) ~[commons-io-2.6.jar!/:2.6]
        at org.apache.commons.io.FileUtils.touch(FileUtils.java:440) ~[commons-io-2.6.jar!/:2.6]
        at org.airsonic.player.service.ApacheCommonsConfigurationService.<init>(ApacheCommonsConfigurationService.java:33) ~[classes!/:10.6.2-RELEASE]
        ... 15 common frames omitted

**Comment by maindrain** [comment]
I had the same issue, and was able to fix it by changing the permissions to the airsonic folder.
