### ISSUE TITLE
Library scan reports "Illegal mix of collations"

### ISSUE THREAD

**Issue by joshuaboniface** [airsonic/airsonic#1801]
## Problem description

During a scan of the library, I'm getting exceptions about "Illegal mix of collations" when my scan gets to ~16500 items.

```
Sep 25 02:03:45 sonic1.i.bonilan.net java[11956]: 2020-09-25 02:03:45.781  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 16750 entries.                                                                      
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]: 2020-09-25 02:03:56.088 ERROR --- o.a.p.s.MediaScannerService              : Failed to scan media library.                                                                                  
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]: org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [select id, path, folder, type, format, title, album, artist, album_artist,
 disc_number, track_number, year, genre, bit_rate, variable_bit_rate, duration_seconds, file_size, width, height, cover_art_path, parent_path, play_count, last_played, comment, created, changed, last_scanned, children_last_updated, present
, version, mb_release_id, mb_recording_id from media_file where path=?]; SQL state [HY000]; error code [1267]; (conn=2114152) Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='; nested
 exception is java.sql.SQLException: (conn=2114152) Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:90) ~[spring-jdbc-4.3.25.RELEASE.jar!/:4.3.25.RELEAS
E]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82) ~[spring-jdbc-4.3.25.RELEASE.jar!/:4.3.25.RELEAS
E]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:654) ~[spring-jdbc-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:688) ~[spring-jdbc-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:720) ~[spring-jdbc-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:730) ~[spring-jdbc-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:780) ~[spring-jdbc-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.airsonic.player.dao.AbstractDao.query(AbstractDao.java:93) ~[classes!/:10.6.2-RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.airsonic.player.dao.AbstractDao.queryOne(AbstractDao.java:159) ~[classes!/:10.6.2-RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.airsonic.player.dao.MediaFileDao.getMediaFile(MediaFileDao.java:68) ~[classes!/:10.6.2-RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.airsonic.player.dao.MediaFileDao$$FastClassBySpringCGLIB$$15ad9359.invoke(<generated>) ~[classes!/:10.6.2-RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736) ~[spring-aop-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) ~[spring-tx-4.3.25.RELEASE.jar!/:4.3.25.REL
EASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671) ~[spring-aop-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.airsonic.player.dao.MediaFileDao$$EnhancerBySpringCGLIB$$d0b397d1.getMediaFile(<generated>) ~[classes!/:10.6.2-RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.airsonic.player.service.MediaFileService.createMediaFile(MediaFileService.java:475) ~[classes!/:10.6.2-RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.airsonic.player.service.MediaFileService.updateChildren(MediaFileService.java:397) ~[classes!/:10.6.2-RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.airsonic.player.service.MediaFileService.getChildrenOf(MediaFileService.java:193) ~[classes!/:10.6.2-RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:240) [classes!/:10.6.2-RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:244) [classes!/:10.6.2-RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.airsonic.player.service.MediaScannerService.doScanLibrary(MediaScannerService.java:183) [classes!/:10.6.2-RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.airsonic.player.service.MediaScannerService.access$000(MediaScannerService.java:50) [classes!/:10.6.2-RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.airsonic.player.service.MediaScannerService$1.run(MediaScannerService.java:151) [classes!/:10.6.2-RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]: Caused by: java.sql.SQLException: (conn=2114152) Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:262) ~[mariadb-java-client-2.5.4.jar!/:na]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164) ~[mariadb-java-client-2.5.4.jar!/:na]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:258) ~[mariadb-java-client-2.5.4.jar!/:na]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:225) ~[mariadb-java-client-2.5.4.jar!/:na]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:145) ~[mariadb-java-client-2.5.4.jar!/:na]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.mariadb.jdbc.ClientSidePreparedStatement.executeQuery(ClientSidePreparedStatement.java:159) ~[mariadb-java-client-2.5.4.jar!/:na]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122) ~[commons-dbcp2-2.7.0.jar!/:2.7.0]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:696) ~[spring-jdbc-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:638) ~[spring-jdbc-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         ... 24 common frames omitted
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]: Caused by: java.sql.SQLException: Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='                                                 
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1598) ~[mariadb-java-client-2.5.4.jar!/:na]                                  
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1460) ~[mariadb-java-client-2.5.4.jar!/:na]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1423) ~[mariadb-java-client-2.5.4.jar!/:na]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:240) ~[mariadb-java-client-2.5.4.jar!/:na]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:216) ~[mariadb-java-client-2.5.4.jar!/:na]
Sep 25 02:03:56 sonic1.i.bonilan.net java[11956]:         ... 30 common frames omitted
```

I'm using MariaDB 10.3 as the backend, and I've confirmed that my database settings are explicitly set to `utf8`:

```
MariaDB [(none)]> create database sonic;                   
Query OK, 1 row affected (0.024 sec)     
MariaDB [(none)]> grant all on sonic.* to airsonic;                              
Query OK, 0 rows affected (0.026 sec)  
MariaDB [(none)]> ALTER DATABASE sonic CHARACTER SET utf8 COLLATE utf8_general_ci;
Query OK, 1 row affected (0.023 sec)
MariaDB [(none)]> Bye
joshua@sonic-db1.i.bonilan.net ~ $ sudo mysql sonic < sonic.sql
```

### Steps to reproduce

1. Scan library.
2. To be honest, this might be a me thing, or might be an obscure bug. I've had a single contiguous instance for almost 2 years now, upgrading through 10.5.X an 10.6.X.

## System information

 * **Airsonic version**: 10.6.2
 * **Operating system**: Debian GNU/Linux 10.x "Buster"
 * **Java version**: OpenJDK 1.8.0_212
 * **Proxy server**: HAProxy
 * **Client**: Firefox 68
 * **Language**: English

## Additional notes

Hopefully there's a quick fix to avoid having to rebuild my library from scratch. Maybe something I can do on the MySQL side?

**Comment by joshuaboniface** [comment]
I thought it might be because I was using an ancient JDBC connector (1.5.7) but I upgraded to the latest (2.7.0) with no change.

**Comment by joshuaboniface** [comment]
I also decided to try a brand new database, same issue. I suspect that it's one particular file doing this, but can't confirm since the log isn't that granular.

**Comment by joshuaboniface** [comment]
So I'm still not certain what was going on, but I decided to take this opportunity to ditch my MariaDB-based database and replace it with a PostgreSQL database to match most of my other services. Now it's working flawlessly. I'm closing this issue as no longer affecting me.
