### ISSUE TITLE
 Main process exited, code=killed, status=31/SYS and Main process exited, code=exited, status=1/FAILURE

### ISSUE THREAD

**Issue by Vince0511** [airsonic/airsonic#1822]
## Problem description

*Airsonic crashes*
```
● airsonic.service - Airsonic Media Server
     Loaded: loaded (/etc/systemd/system/airsonic.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2020-11-10 10:58:57 UTC; 1s ago
    Process: 1461378 ExecStart=/usr/bin/java $JAVA_OPTS -Dairsonic.home=${AIRSONIC_HOME} -Dserver.servlet.contextPath=${CONTEXT_PATH} -Dserver.port=${PORT} -jar ${JAVA_JAR} $JAVA_ARGS (code=exited, status=1/FAI>
   Main PID: 1461378 (code=exited, status=1/FAILURE)

Nov 10 10:58:56 ubuntu20 java[1461378]:         at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_272]
Nov 10 10:58:56 ubuntu20 java[1461378]:         at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[na:1.8.0_272]
Nov 10 10:58:56 ubuntu20 java[1461378]:         at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:153) ~[spring-jdbc-4.3.25.RELEASE.jar!/>
Nov 10 10:58:56 ubuntu20 java[1461378]:         at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:144) ~[spring-jdbc-4.3.25.RELEASE.jar!/:4.3.25>
Nov 10 10:58:56 ubuntu20 java[1461378]:         at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:196) ~[spring-jdbc-4.3.25.RELEASE.>
Nov 10 10:58:56 ubuntu20 java[1461378]:         at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:159) ~[spring-jdbc-4.3.25.RELEASE.jar!/:4.3.>
Nov 10 10:58:56 ubuntu20 java[1461378]:         at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:311) ~[liquibase-core-3.8.7.jar!/:na]
Nov 10 10:58:56 ubuntu20 java[1461378]:         ... 69 common frames omitted
Nov 10 10:58:57 ubuntu20 systemd[1]: airsonic.service: Main process exited, code=exited, status=1/FAILURE
Nov 10 10:58:57 ubuntu20 systemd[1]: airsonic.service: Failed with result 'exit-code'.

```

### Steps to reproduce

*Wait between 2 and 30 seconds for it to crash*

## System information

 * **Airsonic version**: *v10.6.2*
 * **Operating system**: *Ubuntu-server 20.04 LTS*
 * **Java version**: *1.8.0_272*
 * **Proxy server**: *No, not yet*
 * **Client**: *Google Chrome 86.0.4240.193 (on Windows 10)*
 * **Language**: *Dutch / English*

**Comment by Vince0511** [comment]
I've fixed it.
The user 'airsonic' didn't had the right permissions on /var/airsonic.
Now it does!
