### ISSUE TITLE
Unable to start embedded Tomcat in development

### ISSUE THREAD

**Issue by macguirerintoul** [airsonic/airsonic#1834]
## Problem description

I'm unable to run the app in development on macOS Catalina 10.15.7, or the VS Code dev containers (Java 8 and Java 11) [ from here](https://github.com/Microsoft/vscode-dev-containers). I get several errors about the Tomcat server, shown below. This happens on the `release-10.6` branch.

```
2020-12-19 02:38:05.620  INFO --- org.airsonic.player.Application          : Detected Tomcat web server
2020-12-19 02:38:09.484  WARN --- o.a.p.s.GlobalSecurityConfig             : Generating new jwt key
2020-12-19 02:38:10.924 ERROR --- o.s.b.c.e.tomcat.TomcatStarter           : Error starting Tomcat context. Exception: java.lang.NullPointerException. Message: null
2020-12-19 02:38:11.026  WARN --- o.a.c.l.WebappClassLoaderBase            : The web application [ROOT] appears to have started a thread named [net.sf.ehcache.CacheManager@6747008e] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.Object.wait(Object.java:502)
 java.util.TimerThread.mainLoop(Timer.java:526)
 java.util.TimerThread.run(Timer.java:505)
2020-12-19 02:38:11.030  WARN --- ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
2020-12-19 02:38:11.210 ERROR --- o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:138) ~[spring-boot-1.5.22.RELEASE.jar:1.5.22.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536) ~[spring-context-4.3.25.RELEASE.jar:4.3.25.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:123) ~[spring-boot-1.5.22.RELEASE.jar:1.5.22.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:666) ~[spring-boot-1.5.22.RELEASE.jar:1.5.22.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:353) ~[spring-boot-1.5.22.RELEASE.jar:1.5.22.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:300) ~[spring-boot-1.5.22.RELEASE.jar:1.5.22.RELEASE]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:135) [spring-boot-1.5.22.RELEASE.jar:1.5.22.RELEASE]
        at org.airsonic.player.Application.main(Application.java:207) [classes/:na]
Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.initialize(TomcatEmbeddedServletContainer.java:135) ~[spring-boot-1.5.22.RELEASE.jar:1.5.22.RELEASE]
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.<init>(TomcatEmbeddedServletContainer.java:87) ~[spring-boot-1.5.22.RELEASE.jar:1.5.22.RELEASE]
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getTomcatEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:535) ~[spring-boot-1.5.22.RELEASE.jar:1.5.22.RELEASE]
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:177) ~[spring-boot-1.5.22.RELEASE.jar:1.5.22.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:162) ~[spring-boot-1.5.22.RELEASE.jar:1.5.22.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:135) ~[spring-boot-1.5.22.RELEASE.jar:1.5.22.RELEASE]
        ... 7 common frames omitted
Caused by: java.lang.NullPointerException: null
        at java.io.SequenceInputStream.nextStream(SequenceInputStream.java:112) ~[na:1.8.0_275]
        at java.io.SequenceInputStream.read(SequenceInputStream.java:211) ~[na:1.8.0_275]
        at java.io.SequenceInputStream.read(SequenceInputStream.java:207) ~[na:1.8.0_275]
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.read(XMLEntityManager.java:2931) ~[na:1.8.0_275]
        at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:302) ~[na:1.8.0_275]
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1895) ~[na:1.8.0_275]
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.peekChar(XMLEntityScanner.java:508) ~[na:1.8.0_275]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2716) ~[na:1.8.0_275]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602) ~[na:1.8.0_275]
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112) ~[na:1.8.0_275]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505) ~[na:1.8.0_275]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842) ~[na:1.8.0_275]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771) ~[na:1.8.0_275]
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[na:1.8.0_275]
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) ~[na:1.8.0_275]
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643) ~[na:1.8.0_275]
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:228) ~[jaxb-runtime-2.3.2.jar:2.3.2]
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:199) ~[jaxb-runtime-2.3.2.jar:2.3.2]
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157) ~[na:1.8.0_275]
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:204) ~[na:1.8.0_275]
        at org.airsonic.player.spring.RegisterPrecompiledJSPInitializer.parseXmlFragment(RegisterPrecompiledJSPInitializer.java:65) ~[classes/:na]
        at org.airsonic.player.spring.RegisterPrecompiledJSPInitializer.registerPrecompiledJSPs(RegisterPrecompiledJSPInitializer.java:40) ~[classes/:na]
        at org.airsonic.player.spring.RegisterPrecompiledJSPInitializer.onStartup(RegisterPrecompiledJSPInitializer.java:35) ~[classes/:na]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.selfInitialize(EmbeddedWebApplicationContext.java:215) ~[spring-boot-1.5.22.RELEASE.jar:1.5.22.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.access$000(EmbeddedWebApplicationContext.java:91) ~[spring-boot-1.5.22.RELEASE.jar:1.5.22.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext$1.onStartup(EmbeddedWebApplicationContext.java:205) ~[spring-boot-1.5.22.RELEASE.jar:1.5.22.RELEASE]
        at org.springframework.boot.context.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:53) ~[spring-boot-1.5.22.RELEASE.jar:1.5.22.RELEASE]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5154) ~[tomcat-embed-core-8.5.51.jar:8.5.51]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-8.5.51.jar:8.5.51]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412) ~[tomcat-embed-core-8.5.51.jar:8.5.51]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402) ~[tomcat-embed-core-8.5.51.jar:8.5.51]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_275]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_275]
```

### Steps to reproduce

1. Clone repo on `release-10.6` branch
2. (optional) open the Airsonic repo within a dev container
3. Run `Application.java`

## System information

 * **Airsonic version**: 10.6
 * **Operating system**: macOS Catalina 10.15.7, or the VS Code dev containers (Java 8 and Java 11)
 * **Java version**: *the Java version you are using to run Airsonic.*
 
macOS:
```
java 13.0.1 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
```

Java 11 container:
```
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment 18.9 (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9.1+1, mixed mode)
```

 * **Proxy server**: None
 * **Client**: Can't run app
 * **Language**: English

**Comment by tamland** [comment]
I believe this has something to do with jsp compilation. Only solution I've found is to run `mvn package` manually once, which does some magic.. After that, running `Application.java` directly works. At least with intellij. Should resolve #1833 too.

**Comment by yisiliang** [comment]
Same issue with tomcat 8.5, but works well with tomcat 9.
