### ISSUE TITLE
postgresql  ERROR while scanning media folder

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#339]
<a href="https://github.com/cascooscuro"><img src="https://avatars2.githubusercontent.com/u/5746813?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cascooscuro](https://github.com/cascooscuro)**
_Thursday Apr 06, 2017 at 10:57 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/337_

----

Hi,

wile scanning media folder, Libresonic throws an error and stops the scan:

[2017-04-06 12:20:12,027] INFO MediaScannerService - Scanned media library with 10750 entries.
[2017-04-06 12:20:13,776] ERROR MediaScannerService - Failed to scan media library.
org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [update media_file set folder=?,type=?,format=?,title=?,album=?,artist=?,album_artist=?,disc_number=?,track_number=?,year=?,genre=?,bit_rate=?,variable_bit_rate=?,duration_seconds=?,file_size=?,width=?,height=?,cover_art_path=?,parent_path=?,play_count=?,last_played=?,comment=?,changed=?,last_scanned=?,children_last_updated=?,present=?, version=? where path=?]; ERROR: invalid byte sequence for encoding "UTF8": 0x00; nested exception is org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding "UTF8": 0x00
        at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:102)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:870)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:931)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:941)
        at org.libresonic.player.dao.AbstractDao.update(AbstractDao.java:82)
        at org.libresonic.player.dao.MediaFileDao.createOrUpdateMediaFile(MediaFileDao.java:164)
        at org.libresonic.player.dao.MediaFileDao$$FastClassBySpringCGLIB$$83a0b56b.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
        at org.libresonic.player.dao.MediaFileDao$$EnhancerBySpringCGLIB$$17d6a963.createOrUpdateMediaFile(<generated>)
        at org.libresonic.player.service.MediaFileService.getMediaFile(MediaFileService.java:105)
        at org.libresonic.player.service.MediaFileService.getMediaFile(MediaFileService.java:67)
        at org.libresonic.player.service.MediaFileService.findCoverArt(MediaFileService.java:607)
        at org.libresonic.player.service.MediaFileService.createMediaFile(MediaFileService.java:521)
        at org.libresonic.player.service.MediaFileService.updateChildren(MediaFileService.java:393)
        at org.libresonic.player.service.MediaFileService.getChildrenOf(MediaFileService.java:179)
        at org.libresonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:230)
        at org.libresonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:234)
        at org.libresonic.player.service.MediaScannerService.doScanLibrary(MediaScannerService.java:172)
        at org.libresonic.player.service.MediaScannerService.access$000(MediaScannerService.java:38)
        at org.libresonic.player.service.MediaScannerService$2.run(MediaScannerService.java:142)
Caused by: org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding "UTF8": 0x00
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
        at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:97)
        at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:97)
        at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:877)
        at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:870)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
        ... 26 more

I'm Using:
Version	6.2.beta1 – March 5, 2017
Server	Apache Tomcat/8.0.41, java 1.8.0_121, Linux (448.3 MB / 940.5 MB)
and postgre DB in "jndi" mode :

        driverClassName="org.postgresql.Driver"
        url="jdbc:postgresql://localhost/libresonic?stringtype=unspecified"/>

**Comment by Yetangitu** [comment]
Just got bitten by this in current (10.5.0-SNAPSHOT) with Postgresql, will try to find what file causes it and how this can be fixed.

**Comment by Yetangitu** [comment]
The problem is that Postgresql uses C strings internally which can not contain `\0` characters as those are mark the end of such strings. The Postgresql JDBC driver throws an error and does not offer any means to alter this behaviour since it does not munge data in any way (https://github.com/pgjdbc/pgjdbc/issues/665). There are two possible solutions, either all `\0` characters should be filtered out of strings before they touch JDBC or the column type in Postgresql should be changes from `character varying` to `bytea` (byte array) which _does_ allow `\0` characters. The former is probably the best solution given that there is no reason for `\0` characters to appear in text strings to being with.

In my case the culprit was a _genre_ tag which contained `\u0000`:

```
  "genre" : "Text=\" \u0000\"; ",
```

The most sensible solution is to sanitise the data in the _setters_ even if other databases do not suffer from this problem given that it leads to a cleaner data set. Given that Airsonic itself does not produce these `\0` characters I'd start by sanitising the data produced by external sources: metadata extracted from files or scraped off the 'net. See PR #1236 for a possible solution
