### ISSUE TITLE
Review libresonic #476 (CUE sheet support for single-track albums)

### ISSUE THREAD

**Issue by muff1nman** [airsonic/airsonic#495]
PR https://github.com/Libresonic/libresonic/pull/476 looks promising and would resolve #303. Only thing that is really bothersome is the jitpack dependency. Does anyone have CUE type media they could test with?

**Comment by jooola** [comment]
Why not simply ask the PR owner to post it here also ? (on airsonic) 🤣

**Comment by korden32** [comment]
I would be happy to test & use CUE support, but as I already commented at the original PR, it doesn't work for me - CUE parsing itsef is working and I see tracks in the database, but I can't play such tracks - it throws an error

```
java.lang.SecurityException: Access denied to file Intro
        at org.airsonic.player.service.MediaFileService.getMediaFile(MediaFileService.java:141) ~[classes!/:10.0.0-RELEASE]
        at org.airsonic.player.controller.CoverArtController.createMediaFileCoverArtRequest(CoverArtController.java:180) ~[classes!/:10.0.0-RELEASE]
        at org.airsonic.player.controller.CoverArtController.createCoverArtRequest(CoverArtController.java:150) ~[classes!/:10.0.0-RELEASE]
...
```
It probably requires some fixes in getFile or getSingleFileAlbumSongWholePath 

I can provide example flac+cue for testing if needed

**Comment by tesshucom** [comment]
At Airsonic, #856 looks like successor work. I'll close it. If there is a problem, please reopen it.
