### ISSUE TITLE
Migration from LS 6.2.1 to AS 10.0.0 fails with exception

### ISSUE THREAD

**Issue by nRaecheR** [airsonic/airsonic#532]
I've tried to migrate my working Libresonic v6.2.1 installation to Airsonic v10.0.0. I renamed all files in the copied Libresonic data directory to airsonic.* and started Airsonic. The log output is as follows: 

```
2017-08-23 15:02:52.242  INFO --- o.a.player.boot.Application              : Starting Application v10.0.0-RELEASE on d56ce1bfef93 with PID 7 (/airsonic/airsonic.war started by root in /airsonic)
2017-08-23 15:02:52.256  INFO --- o.a.player.boot.Application              : The following profiles are active: legacy
2017-08-23 15:02:59.010  INFO --- o.a.p.service.SettingsService            : Java: 1.8.0_131, OS: Linux
2017-08-23 15:03:37.493  INFO --- liquibase                                : Successfully acquired change log lock
2017-08-23 15:03:40.601  INFO --- liquibase                                : Reading from DATABASECHANGELOG
2017-08-23 15:03:40.948  INFO --- liquibase                                : Successfully released change log lock
2017-08-23 15:03:40.949 ERROR --- o.a.p.spring.SpringLiquibase             : ===============================================
2017-08-23 15:03:40.950 ERROR --- o.a.p.spring.SpringLiquibase             : An exception occurred during database migration
2017-08-23 15:03:40.951 ERROR --- o.a.p.spring.SpringLiquibase             : A rollback file has been generated at /airsonic/data/rollback.sql
2017-08-23 15:03:40.951 ERROR --- o.a.p.spring.SpringLiquibase             : Execute it within your database to rollback any changes
2017-08-23 15:03:40.961 ERROR --- o.a.p.spring.SpringLiquibase             : The exception is as follows


liquibase.exception.ValidationFailedException: Validation Failed:
     1 change sets check sum
          classpath:liquibase/legacy/schema26.xml::schema26_002::muff1nman was: 7:d55e425a3d6d34145545ec6d9f1fe264 but is now: 7:68fbcbce1222f707be26b4c52b0e7366

	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:266) ~[liquibase-core-3.5.1.jar!/:na]
	at liquibase.Liquibase.futureRollbackSQL(Liquibase.java:935) ~[liquibase-core-3.5.1.jar!/:na]
	at liquibase.Liquibase.futureRollbackSQL(Liquibase.java:912) ~[liquibase-core-3.5.1.jar!/:na]
	at liquibase.Liquibase.futureRollbackSQL(Liquibase.java:891) ~[liquibase-core-3.5.1.jar!/:na]
	at liquibase.integration.spring.SpringLiquibase.generateRollbackFile(SpringLiquibase.java:414) ~[liquibase-core-3.5.1.jar!/:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:390) ~[liquibase-core-3.5.1.jar!/:na]
	at org.airsonic.player.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:25) ~[classes!/:10.0.0-RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) [spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) [spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) [spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) [spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) [spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) [spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) [spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) [spring-boot-1.4.5.RELEASE.jar!/:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762) [spring-boot-1.4.5.RELEASE.jar!/:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:372) [spring-boot-1.4.5.RELEASE.jar!/:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-1.4.5.RELEASE.jar!/:1.4.5.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.4.5.RELEASE.jar!/:1.4.5.RELEASE]
	at org.airsonic.player.boot.Application.main(Application.java:219) [classes!/:10.0.0-RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [airsonic.war:10.0.0-RELEASE]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [airsonic.war:10.0.0-RELEASE]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [airsonic.war:10.0.0-RELEASE]
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) [airsonic.war:10.0.0-RELEASE]
```

The WAR runs on a modified Docker image, adapted from the Airsonic git repo, just adding some needed java parameters (increase of java memory). 

Is there anything I can to successfully migrate the database and my installation to AS 10.0.0 ?

**Comment by muff1nman** [comment]
This should be fixed in 10.0.1 which should be released tonight

**Comment by nRaecheR** [comment]
Yes, it works now, thank you very much.

**Comment by seanvree** [comment]
@nRaecheR  I'm getting this same error. Was working great for a few weeks, for some reason last night I get these errors below:

OS: windows 10E x64 1703
Airsonic: 10.0.1
mysql: 5.7.19

```
C:\WINDOWS\system32>cd C:\airsonic

C:\airsonic>java -Dserver.port=30800 -Dserver.context-path=/airsonic -jar airsonic.war
           _                       _
     /\   (_)                     (_)
    /  \   _ _ __  ___  ___  _ __  _  ___
   / /\ \ | | '__|/ __|/ _ \| '_ \| |/ __|
  / ____ \| | |   \__ \ (_) | | | | | (__
 /_/    \_\_|_|   |___/\___/|_| |_|_|\___|

                        10.0.1-RELEASE



2017-10-06 09:36:56.175  INFO --- o.a.player.boot.Application              : Starting Application v10.0.1-RELEASE on VreePlexDesktop with PID 29648 (C:\airsonic\airsonic.war started by Administrator in C:\airsonic)
2017-10-06 09:36:56.181  INFO --- o.a.player.boot.Application              : The following profiles are active: legacy
2017-10-06 09:36:58.643  INFO --- o.a.p.service.SettingsService            : Java: 1.8.0_144, OS: Windows 10
2017-10-06 09:37:06.271 ERROR --- o.a.p.spring.SpringLiquibase             : ===============================================
2017-10-06 09:37:06.271 ERROR --- o.a.p.spring.SpringLiquibase             : An exception occurred during database migration
2017-10-06 09:37:06.274 ERROR --- o.a.p.spring.SpringLiquibase             : A rollback file has been generated at c:\airsonic\rollback.sql
2017-10-06 09:37:06.274 ERROR --- o.a.p.spring.SpringLiquibase             : Execute it within your database to rollback any changes
2017-10-06 09:37:06.281 ERROR --- o.a.p.spring.SpringLiquibase             : The exception is as follows


liquibase.exception.DatabaseException: java.sql.SQLException: File input/output error: java.io.IOException: org.hsqldb.HsqlException: Unexpected token:
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:393) ~[liquibase-core-3.5.1.jar!/:na]
        at org.airsonic.player.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:25) ~[classes!/:10.0.1-RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) [spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) [spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) [spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) [spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) [spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) [spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) [spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) [spring-boot-1.4.5.RELEASE.jar!/:1.4.5.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762) [spring-boot-1.4.5.RELEASE.jar!/:1.4.5.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:372) [spring-boot-1.4.5.RELEASE.jar!/:1.4.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-1.4.5.RELEASE.jar!/:1.4.5.RELEASE]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.4.5.RELEASE.jar!/:1.4.5.RELEASE]
        at org.airsonic.player.boot.Application.main(Application.java:219) [classes!/:10.0.1-RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_144]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_144]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [airsonic.war:10.0.1-RELEASE]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [airsonic.war:10.0.1-RELEASE]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [airsonic.war:10.0.1-RELEASE]
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) [airsonic.war:10.0.1-RELEASE]
Caused by: java.sql.SQLException: File input/output error: java.io.IOException: org.hsqldb.HsqlException: Unexpected token:
        at org.hsqldb.jdbc.Util.sqlException(Unknown Source) ~[hsqldb-1.8.0.7.jar!/:private-2006/09/24-10:30:15]
        at org.hsqldb.jdbc.jdbcConnection.<init>(Unknown Source) ~[hsqldb-1.8.0.7.jar!/:private-2006/09/24-10:30:15]
        at org.hsqldb.jdbcDriver.getConnection(Unknown Source) ~[hsqldb-1.8.0.7.jar!/:private-2006/09/24-10:30:15]
        at org.hsqldb.jdbcDriver.connect(Unknown Source) ~[hsqldb-1.8.0.7.jar!/:private-2006/09/24-10:30:15]
        at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_144]
        at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_144]
        at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:153) ~[spring-jdbc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:144) ~[spring-jdbc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:196) ~[spring-jdbc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:159) ~[spring-jdbc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388) ~[liquibase-core-3.5.1.jar!/:na]
        ... 26 common frames omitted

2017-10-06 09:37:06.282 ERROR --- o.a.p.spring.SpringLiquibase             : ===============================================
2017-10-06 09:37:06.284  WARN --- ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [applicationContext-db.xml]: Invocation of init method failed; nested exception is liquibase.exception.DatabaseException: java.sql.SQLException: File input/output error: java.io.IOException: org.hsqldb.HsqlException: Unexpected token:
2017-10-06 09:37:06.851  WARN --- o.s.boot.SpringApplication               : Error handling failed (Error creating bean with name 'delegatingApplicationListener' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metaDataSourceAdvisor': Cannot resolve reference to bean 'methodSecurityMetadataSource' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' available)
2017-10-06 09:37:06.855 ERROR --- o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [applicationContext-db.xml]: Invocation of init method failed; nested exception is liquibase.exception.DatabaseException: java.sql.SQLException: File input/output error: java.io.IOException: org.hsqldb.HsqlException: Unexpected token:
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.5.RELEASE.jar!/:1.4.5.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762) ~[spring-boot-1.4.5.RELEASE.jar!/:1.4.5.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:372) ~[spring-boot-1.4.5.RELEASE.jar!/:1.4.5.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-1.4.5.RELEASE.jar!/:1.4.5.RELEASE]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.4.5.RELEASE.jar!/:1.4.5.RELEASE]
        at org.airsonic.player.boot.Application.main(Application.java:219) [classes!/:10.0.1-RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_144]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_144]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [airsonic.war:10.0.1-RELEASE]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [airsonic.war:10.0.1-RELEASE]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [airsonic.war:10.0.1-RELEASE]
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) [airsonic.war:10.0.1-RELEASE]
Caused by: liquibase.exception.DatabaseException: java.sql.SQLException: File input/output error: java.io.IOException: org.hsqldb.HsqlException: Unexpected token:
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:393) ~[liquibase-core-3.5.1.jar!/:na]
        at org.airsonic.player.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:25) ~[classes!/:10.0.1-RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        ... 23 common frames omitted
Caused by: java.sql.SQLException: File input/output error: java.io.IOException: org.hsqldb.HsqlException: Unexpected token:
        at org.hsqldb.jdbc.Util.sqlException(Unknown Source) ~[hsqldb-1.8.0.7.jar!/:private-2006/09/24-10:30:15]
        at org.hsqldb.jdbc.jdbcConnection.<init>(Unknown Source) ~[hsqldb-1.8.0.7.jar!/:private-2006/09/24-10:30:15]
        at org.hsqldb.jdbcDriver.getConnection(Unknown Source) ~[hsqldb-1.8.0.7.jar!/:private-2006/09/24-10:30:15]
        at org.hsqldb.jdbcDriver.connect(Unknown Source) ~[hsqldb-1.8.0.7.jar!/:private-2006/09/24-10:30:15]
        at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_144]
        at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_144]
        at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:153) ~[spring-jdbc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:144) ~[spring-jdbc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:196) ~[spring-jdbc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:159) ~[spring-jdbc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388) ~[liquibase-core-3.5.1.jar!/:na]
        ... 26 common frames omitted


C:\airsonic>
```

**Comment by muff1nman** [comment]
@seanvree Your error is not the same. Please open a different issue.

**Comment by seanvree** [comment]
@muff1nman  will do. thx.
