### ISSUE TITLE
Java 9 support

### ISSUE THREAD

**Issue by binhex** [airsonic/airsonic#611]
## Problem description
The following exception is seen when attempting to start airsonic 10.1.0 from a previously running airsonic 10.0.1 instance resulting in inability to access the webui or connect via dsub:-

```2017-11-04 19:14:51,951 DEBG 'start-script' stdout output:
2017-11-04 19:14:51.951  WARN --- ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from class path resource [applicationContext-sonos.xml]; nested exception is org.springframework.beans.FatalBeanException: Invalid NamespaceHandler class [org.apache.cxf.jaxws.spring.NamespaceHandler] for namespace [http://cxf.apache.org/jaxws]: problem with handler class file or dependent class; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

2017-11-04 19:14:51,964 DEBG 'start-script' stdout output:
2017-11-04 19:14:51.963 ERROR --- o.s.b.f.s.DefaultListableBeanFactory     : Destroy method on bean with name 'org.springframework.boot.autoconfigure.internalCachingMetadataReaderFactory' threw an exception

java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@57ad2aa7: startup date [Sat Nov 04 19:14:48 GMT 2017]; root of context hierarchy
	at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:414) [spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.context.support.ApplicationListenerDetector.postProcessBeforeDestruction(ApplicationListenerDetector.java:97) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578) [spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554) [spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:961) [spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523) [spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.destroySingletons(FactoryBeanRegistrySupport.java:230) [spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:968) [spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1030) [spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:556) [spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.airsonic.player.Application.main(Application.java:218) [classes!/:10.1.0-RELEASE]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [airsonic.war:10.1.0-RELEASE]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [airsonic.war:10.1.0-RELEASE]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [airsonic.war:10.1.0-RELEASE]
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) [airsonic.war:10.1.0-RELEASE]
```

### Steps to reproduce

Take a running Airsonic 10.0.1 and upgrade to Airsonic 10.1.0

## System information

 * **Airsonic version**: I cant access the about page, but its the 10.1.0 release from github
 * **Operating system**: Arch Linux Docker container.
 * **Proxy server**: None
 * **Client**: Google Chrome browser

## Additional notes

None.

**Comment by muff1nman** [comment]
I am not able to reproduce this with the docker image `airsonic/airsonic:10.1.0-RELEASE`. Startup is fine with or without sonos on. Are you using a third party container?

**Comment by binhex** [comment]
Yes i'm using my own Docker image, you are welcome to create a container, link to docker hub repo:-

https://hub.docker.com/r/binhex/arch-airsonic/

One question, did you try upgrading your configuration from 10.0.1 to 10.1.0? obviously the configuration for airsonic is outside the container so that it's persistent, so i am 'upgrading' the configuration, such as airsonic db.

**Comment by binhex** [comment]
hmm odd, even with no legacy configuration i'm seeing the same issue, i'm beginning to wonder if the issue is somehow related to the Docker image i have created, if you're not seeing the problem with the official docker image. I just dont know what could be causing this blow up, any ideas?

**Comment by binhex** [comment]
note i am running Oracle 9.0.1, possibly this  might be related, you tested airsonic with Orale JRE 9.x?

https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

spotted this line in the exception:-

``
nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
```

**Comment by muff1nman** [comment]
There are known issues with Java 9. I havne't looked at it myself in detail yet, but as far as I know you can add a command line option to enable some modules that are disabled by default in java 9.

**Comment by Whisprin** [comment]
Sorry to just jump in here: I tried running Airsonic with Java 9 too, saw some errors and was just about to create an issue for it.
Should I still go ahead to track Java 9 support or is it just about enabling modules? Can you elaborate @muff1nman ?

Motivation: Unfortunately Java 8 is limiting some features of Airsonic (some https podcasts) which should be available in Java 9.

**Comment by muff1nman** [comment]
@Whisprin let's repurpose this issue for addressing Java9.

**Comment by binhex** [comment]
Thanks muff1nman, for now if will simply use jre8, i hope adding support for jre9 isn't too tough 😁

**Comment by Whisprin** [comment]
The plugin org.jvnet.jaxb2.maven2 which is used in rest-api doesn't support Java 9. Progress tracked here: https://github.com/highsource/maven-jaxb2-plugin/issues/114

**Comment by KingDuckZ** [comment]
This is my configuration, in case it's helpful to other people as well:

    # Set the location of the standalone war to use
    JAVA_JAR=/var/lib/airsonic/airsonic.war
    
    # Set any java opts separated by spaces
    JAVA_OPTS=-Xmx700m --add-modules java.xml.bind,java.xml.ws
    # --add-exports java.base/jdk.internal.ref=ALL-UNNAMED
    
    # Set a different location for airsonic home. 
    # If this path is /var/libresonic or even contains "libresonic",
    # the data from a previous libresonic can be used as is (i.e. without
    # renaming libresonic.properties,db/libresonic*,etc
    AIRSONIC_HOME=/mnt/memorycard
    
    # Change the port to listen on
    PORT=4040
    
    # Change the path that is listened on
    CONTEXT_PATH=/airsonic
    
    # Add any java args. These are different than JAVA_OPTS in that 
    # they are passed directly to the program. The default is empty:
    #JAVA_ARGS=
    
    # Note that there are several settings for spring boot, not explicitly listed
    # here, but can be used in either JAVA_OPTS or JAVA_ARGS. The full list
    # can be found here: 
    # https://docs.spring.io/spring-boot/docs/1.4.5.RELEASE/reference/htmlsingle/#common-application-properties
    # For example to set debug across the board:
    #JAVA_ARGS=--debug
    
    # Or to change the ip address that is listened on:
    JAVA_ARGS=--server.address=192.168.3.9

I think JAVA_OPTS is the important bit in this case.

**Comment by Whisprin** [comment]
Thanks @KingDuckZ I was able to run Airsonic with Java 9 using your JAVA_OPTS. I updated my previous post accordingly.

**Comment by KingDuckZ** [comment]
@Whisprin glad it was of help! please be aware that because of issue #622 mp3 playback will not be perfect. If you leave transcoding options as they are you will probably be able to listen to mp3 files, however I think Airsonic will not be able to read metadata or duration from mp3 files. It seems to work fine with ogg files.

**Comment by KingDuckZ** [comment]
Is this really fixed?

**Comment by jmfarina** [comment]
Hello, my two cents on this. I've managed to get the war version working with Java 9 (9.0.4, to be precise) and Tomcat 9.0.6 by adding missing libraries, which were dropped in Java 9. These links were helpful and explain the problem more clearly: https://www.jesperdj.com/2018/09/30/jaxb-on-java-9-10-11-and-beyond/ and https://stackoverflow.com/questions/48204141/replacements-for-deprecated-jpms-modules-with-java-ee-apis/48204154#48204154
But in a nutshell: Java 9 deprecated some libraries previously included in the runtime environment. As @KingDuckZ pointed out, adding `--add-modules java.xml.bind,java.xml.ws` in JAVA_OPTS enables these deprecated libraries. Problem is, in Java 11 they are removed for good, so this solution is just a patch for Java 9 and 10.

The long term solution, as far as I understand based on my limited research on the subject, is to include these libraries as dependencies of the project. For those who want to get those jars: I've managed to get all the "correct" libraries needed by creating a pom.xml file with the dependencies required, based on the exceptions I got and the information in the links mentioned, running `mvn install` and moving the downloaded libraries from target/my-app-1.0-SNAPSHOT/WEB-INF/lib into the deployed app's WEB-INF/lib library. The only jar I had to omit was the eclipselink-2.6.4.jar, since it seems collided with some other jar already in the PATH.
The sample pom.xml I used:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.mycompany.app</groupId>
  <artifactId>my-app</artifactId>
  <packaging>war</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>my-app</name>
  <url>http://maven.apache.org</url>
  <dependencies>
    <dependency>
        <groupId>org.glassfish.jaxb</groupId>
        <artifactId>jaxb-runtime</artifactId>
        <version>2.3.1</version>
        <scope>runtime</scope>
    </dependency>
    <dependency>
        <groupId>com.sun.xml.ws</groupId>
        <artifactId>jaxws-ri</artifactId>
        <version>2.3.0</version>
        <type>pom</type>
    </dependency>
  </dependencies>
  
  <build>
    <plugins>
      <!-- any other plugins -->
      <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

For those like me who might stumble upon the exceptions and don't know that they are related to this topic, you'll hopefully arrive here looking for java.lang.ClassNotFoundException: javax.xml.bind.JAXBException.
