### ISSUE TITLE
Docker Jukebox Support

### ISSUE THREAD

**Issue by captn3m0** [airsonic/airsonic#642]
## Problem description

Unable to use jukebox while running airsonic inside a Docker container.

### Steps to reproduce

1. Run AirSonic inside a docker container using the official image.
2. Attempt playing a song on the jukebox

I get the following error:

<summary>Error Trace

<details>

```2017-12-03 17:00:05.604  INFO --- o.a.p.io.TranscodeInputStream            : Starting transcoder: [/airsonic/data/transcode/ffmpeg] [-ss] [0] [-i] [/airsonic/music/Adele/21/01 Rolling in the Deep.mp3] [-map] [0:0] [-v] [0] [-ar] [44100] [-ac] [2] [-f] [s16be] [-] 
2017-12-03 17:00:05.637 ERROR --- o.a.p.s.JukeboxLegacySubsonicService     : Error in jukebox: java.lang.IllegalArgumentException: No line matching interface SourceDataLine supporting format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, big-endian is supported.

java.lang.IllegalArgumentException: No line matching interface SourceDataLine supporting format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, big-endian is supported.
	at javax.sound.sampled.AudioSystem.getLine(AudioSystem.java:479) ~[na:1.8.0_131]
	at javax.sound.sampled.AudioSystem.getSourceDataLine(AudioSystem.java:606) ~[na:1.8.0_131]
	at org.airsonic.player.service.jukebox.AudioPlayer.<init>(AudioPlayer.java:62) ~[classes!/:10.1.0-RELEASE]
	at org.airsonic.player.service.JukeboxLegacySubsonicService.play(JukeboxLegacySubsonicService.java:114) [classes!/:10.1.0-RELEASE]
	at org.airsonic.player.service.JukeboxLegacySubsonicService.updateJukebox(JukeboxLegacySubsonicService.java:82) [classes!/:10.1.0-RELEASE]
	at org.airsonic.player.service.JukeboxService.skip(JukeboxService.java:163) [classes!/:10.1.0-RELEASE]
	at org.airsonic.player.controller.SubsonicRESTController.jukeboxControl(SubsonicRESTController.java:864) [classes!/:10.1.0-RELEASE]
	at sun.reflect.GeneratedMethodAccessor352.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) [spring-web-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) [spring-webmvc-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) [spring-webmvc-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) [spring-webmvc-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) [spring-webmvc-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) [spring-webmvc-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) [spring-webmvc-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet-api-3.1.0.jar!/:3.1.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar!/:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841) [jetty-servlet-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650) [jetty-servlet-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206) [websocket-server-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) [jetty-servlet-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.airsonic.player.security.JWTRequestParameterProcessingFilter.doFilter(JWTRequestParameterProcessingFilter.java:61) [classes!/:10.1.0-RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) [jetty-servlet-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.airsonic.player.filter.MetricsFilter.doFilter(MetricsFilter.java:30) [classes!/:10.1.0-RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) [jetty-servlet-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.airsonic.player.filter.RequestEncodingFilter.doFilter(RequestEncodingFilter.java:45) [classes!/:10.1.0-RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) [jetty-servlet-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.airsonic.player.filter.RESTFilter.doFilter(RESTFilter.java:53) [classes!/:10.1.0-RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) [jetty-servlet-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.airsonic.player.filter.ParameterDecodingFilter.doFilter(ParameterDecodingFilter.java:57) [classes!/:10.1.0-RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) [jetty-servlet-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.airsonic.player.filter.BootstrapVerificationFilter.doFilter(BootstrapVerificationFilter.java:55) [classes!/:10.1.0-RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) [jetty-servlet-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.airsonic.player.security.RESTRequestParameterProcessingFilter.doFilter(RESTRequestParameterProcessingFilter.java:123) [classes!/:10.1.0-RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177) [spring-security-web-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347) [spring-web-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263) [spring-web-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) [jetty-servlet-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) [jetty-servlet-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108) [spring-web-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) [jetty-servlet-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) [spring-web-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) [jetty-servlet-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) [jetty-servlet-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) [jetty-servlet-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [jetty-security-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190) [jetty-server-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) [jetty-server-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) [jetty-server-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) [jetty-server-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) [jetty-server-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [jetty-servlet-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) [jetty-server-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) [jetty-server-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) [jetty-server-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.server.Server.handle(Server.java:561) [jetty-server-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:334) [jetty-server-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104) [jetty-io-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247) [jetty-util-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140) [jetty-util-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243) [jetty-util-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679) [jetty-util-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597) [jetty-util-9.4.7.v20170914.jar!/:9.4.7.v20170914]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

```
</details>
</summary>

## System information

 * **Airsonic version**: 10.1.0-RELEASE – November 4, 2017
 * **Operating system**: ArchLinux, running using Docker version 17.10.0-ce
 * **Proxy server**: [Traefik v 1.5.0-rc1](https://github.com/containous/traefik/releases/tag/v1.5.0-rc1)
 * **Client**: Ultrasonic

**Comment by captn3m0** [comment]
I'm running pulseaudio on the host, and I'd prefer getting the docker container working against that.

**Comment by jooola** [comment]
I have to admit, last time i tried to set up jukebox it was not that easy and the feature itself isn't really working a lot, still I suggest you to try, since I'm absolutely not a jukebox pro ( never use it ).

First thing to do is to set up the Java audio output device I think.
After you might need to find a way to bridge this devices to the outside of your docker (this is docker related not airsonic ).

I got it working by adding the following line to the airsonic start script :

**Comment by retro-78** [comment]
Hi 

This is working for me on a libresonic container :

1) Install the latest version of `docker-ce` package, the installation procedure is described [here](https://store.docker.com/editions/community/docker-ce-server-ubuntu?tab=description).
2) On the host machine change the owner of the device /dev/snd with the command below.
```
$ chown -R $YOURDOCKERUSER:$YOURDOCKEGROUP /dev/snd
```
3) Run docker with a non root user.

- Add $YOURDOCKERUSER to the docker group.
```
$ sudo usermod -aG docker $YOURDOCKERUSER
```
- Restart your host machine.

- After the reboot, the 'docker' group should appear with the command `groups`.
```
$ groups
```
4) Get the user and group id of $YOURDOCKERUSER.

For getting the user id \:
```
$ id -u $YOURDOCKERUSER
```
For getting the group id\:
```
$ id -g $YOURDOCKERGROUP
```
5) Create the container and indicate PID and GID of this user.

```
$ docker create \
--name="libresonic" \
-v </path/to/config>:/config \
-v </path/to/music>:/music \
-v </path/to/playlists>:/playlists \
-v </path/to/podcasts>:/podcasts \
-v </path/to/other media>:/media \
--device=/dev/snd \
-e PGID=<yourdockergroupid> -e PUID=<yourdockeruserid> \
-e CONTEXT_PATH=<url-base> \
-e TZ=<timezone> \
-p 4040:4040 \
linuxserver/libresonic
```
6) Finally, start the container.
```
$ docker start libresonic
```

**Comment by captn3m0** [comment]
I'll try this out tonight and report back. I have added the dockeruser to the audio group, which is what Archlinux recommends, but haven't tried the libresonic image yet.

**Comment by retro-78** [comment]
@captn3m0 is this working for you ? If it is the case please close this issue =).

**Comment by retro-78** [comment]
If thoose steps are working maybe we should add informations for using jukebox inside the container in the Advanced Configuration part of the official documentation.

**Comment by captn3m0** [comment]
Testing this out right now. My original config is in terraform which [doesn't support the `--device` parameter yet][0]. I do have the correct group associations though. Testing this out with the airsonic container. Will close the issue if this works with just plain docker.

I can use the `--privileged` flag in terraform for now as a workaround, if this works.

[0]: https://github.com/terraform-providers/terraform-provider-docker/issues/30

**Comment by captn3m0** [comment]
`--device` stops the error, but I still get no sound.

Config:

```
export TZ="Asia/Kolkata"

docker run \
-v /home/nemo/airsonic/music:/music \
-v /home/nemo/airsonic/config:/config \
-v /home/nemo/airsonic/podcasts:/podcasts \
-v /home/nemo/airsonic/playlists:/playlists \
-e PGID=92 -e PUID=619 \
--device /dev/snd \
--privileged \
-e "TZ=$TZ" \
-p 4040:4040 \
linuxserver/libresonic
```

<details>
<summary>Log</summary>

```
bash airsonic.sh 
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \ 
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------

User uid:    619
User gid:    92
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2017-12-30 21:19:14.215:INFO::main: Logging initialized @833ms
2017-12-30 21:19:14.241:INFO:oejr.Runner:main: Runner
2017-12-30 21:19:14.734:INFO:oejs.Server:main: jetty-9.3.14.v20161028
2017-12-30 21:19:19.488:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=3742ms
2017-12-30 21:19:19.884:INFO:/:main: 2 Spring WebApplicationInitializers detected on classpath
  _      _ _                               _       ______
 | |    (_) |                             (_)      \ \ \ \
 | |     _| |__  _ __ ___  ___  ___  _ __  _  ___   | | | |
 | |    | | '_ \| '__/ _ \/ __|/ _ \| '_ \| |/ __|  | | | |
 | |____| | |_) | | |  __/\__ \ (_) | | | | | (__   | | | |
 |______|_|_.__/|_|  \___||___/\___/|_| |_|_|\___|  | | | |
                                                   /_/_/_/
                                

2017-12-30 21:19:21.839  INFO --- o.l.player.boot.Application              : Starting Application on b6ef5c23eb9a with PID 197 (/tmp/jetty-0.0.0.0-4040-libresonic.war-_-any-1141503368490643322.dir/webapp/WEB-INF/classes started by abc in /app/libresonic)
2017-12-30 21:19:21.842  INFO --- o.l.player.boot.Application              : The following profiles are active: legacy
2017-12-30 21:19:24.657  INFO --- o.l.p.service.SettingsService            : Java: 1.8.0_151, OS: Linux
2017-12-30 21:19:24.664:INFO:/:main: Initializing Spring embedded WebApplicationContext
2017-12-30 21:19:28.580  INFO --- liquibase                                : Successfully acquired change log lock
2017-12-30 21:19:30.188  INFO --- liquibase                                : Reading from DATABASECHANGELOG
2017-12-30 21:19:30.349  INFO --- liquibase                                : Successfully released change log lock
2017-12-30 21:19:30.355  INFO --- liquibase                                : Successfully acquired change log lock
2017-12-30 21:19:30.364  INFO --- liquibase                                : Reading from DATABASECHANGELOG
2017-12-30 21:19:30.457  INFO --- liquibase                                : Successfully released change log lock
2017-12-30 21:19:30.837  INFO --- o.l.p.s.MediaScannerService              : Automatic media library scanning scheduled to run every 1 day(s), starting at Sun Dec 31 03:00:00 IST 2017
2017-12-30 21:19:30.905  INFO --- o.l.p.service.PodcastService             : Automatic Podcast update scheduled to run every 24 hour(s), starting at Sat Dec 30 21:24:30 IST 2017
2017-12-30 21:19:31.000  INFO --- o.l.player.service.UPnPService           : Starting UPnP service...
2017-12-30 21:19:31.422  INFO --- o.l.player.service.UPnPService           : Disabling UPnP/DLNA media server
2017-12-30 21:19:31.422  INFO --- o.l.player.service.UPnPService           : Starting UPnP service - Done!
2017-12-30 21:19:34.630  INFO --- o.l.player.boot.Application              : Started Application in 14.539 seconds (JVM running for 21.258)
2017-12-30 21:19:34.844:INFO:/:main: Initializing Spring FrameworkServlet 'dispatcherServlet'
2017-12-30 21:19:34.893:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@769c9116{/,file:///tmp/jetty-0.0.0.0-4040-libresonic.war-_-any-1141503368490643322.dir/webapp/,AVAILABLE}{file:///app/libresonic/libresonic.war}
2017-12-30 21:19:34.934:INFO:oejs.AbstractConnector:main: Started ServerConnector@6af0407c{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
2017-12-30 21:19:34.934:INFO:oejs.Server:main: Started @21562ms

2017-12-30 21:21:13.928  INFO --- o.l.p.c.StreamController                 : Got HTTP range: 0-
2017-12-30 21:21:13.938  INFO --- o.l.p.io.PlayQueueInputStream            : admin listening to "One More Light Live/08. Crawling (One More Light Live).mp3"
2017-12-30 21:21:27.557  INFO --- o.l.player.dao.PlayerDao                 : Created player 2.
...
2017-12-30 21:22:18.699  INFO --- o.l.p.service.JukeboxService             : admin stopping jukebox for "Song.mp3"
2017-12-30 21:22:18.703  INFO --- o.l.p.io.TranscodeInputStream            : Starting transcoder: [/config/transcode/ffmpeg] [-ss] [0] [-i] [/music/Music/Song.mp3] [-map] [0:0] [-v] [0] [-ar] [44100] [-ac] [2] [-f] [s16be] [-] 
2017-12-30 21:22:18.776  INFO --- o.l.p.service.JukeboxService             : admin starting jukebox for "Song.mp3"
```
</details>

I get the same result if I remove `--privileged`. The owerships and user relationships:

```
$ id lounge
uid=619(lounge) gid=619(lounge) groups=619(lounge),92(audio)
$ ls -la /dev/snd
total 0
drwxr-xr-x   3 root root      320 Dec 30 18:04 ./
drwxr-xr-x  19 root root     3.4K Dec 30 21:27 ../
drwxr-xr-x   2 root root       80 Dec 30 18:04 by-path/
crw-rw----+  1 root audio 116,  6 Dec 30 18:04 controlC0
crw-rw----+  1 root audio 116,  2 Dec 30 18:04 controlC1
crw-rw----+  1 root audio 116, 12 Dec 30 18:04 hwC0D0
crw-rw----+  1 root audio 116,  5 Dec 30 18:04 hwC1D0
crw-rw----+  1 root audio 116, 11 Dec 30 18:05 pcmC0D10p
crw-rw----+  1 root audio 116,  7 Dec 30 18:05 pcmC0D3p
crw-rw----+  1 root audio 116,  8 Dec 30 21:27 pcmC0D7p
crw-rw----+  1 root audio 116,  9 Dec 30 19:58 pcmC0D8p
crw-rw----+  1 root audio 116, 10 Dec 30 18:05 pcmC0D9p
crw-rw----+  1 root audio 116,  4 Dec 30 21:27 pcmC1D0c
crw-rw----+  1 root audio 116,  3 Dec 30 21:27 pcmC1D0p
crw-rw----+  1 root audio 116,  1 Dec 30 18:04 seq
crw-rw----+  1 root audio 116, 33 Dec 30 18:04 timer
```

I attempted running it with the `--user` flag as well, but that didn't work either. I've killed pulseaudio and [verified](https://stackoverflow.com/q/526132) that no other process is using `/dev/snd`.

I'm going to try running it directly on the host without docker next.

**Comment by jooola** [comment]
To set up jukebox , you need to add on which device the Application needs to set his audio.

Something like this:
```
-Djavax.sound.sampled.SourceDataLine='default [default]
```
And change default with something more precise if not the default

Also see: http://forum.subsonic.org/forum/viewtopic.php?f=2&t=2038

I think you need to search a bit on the net. And any contribution to the documentation will be really appreciated !

**Comment by captn3m0** [comment]
Thanks for being patient with this. I got it working against by mounting `sound.properties` into the container:

```
javax.sound.sampled.Clip=#PCH [plughw:1,0]
javax.sound.sampled.Port=#Port PCH [hw:1]
javax.sound.sampled.SourceDataLine=#PCH [plughw:1,0]
javax.sound.sampled.TargetDataLine=#PCH [plughw:1,0] 
```
`/usr/lib/jvm/java-1.8-openjdk/jre/lib/sound.properties`

However, it seems to be using alsa directly, and not pulseaudio. I'll put my findings in the docs.

**Comment by captn3m0** [comment]
Since this is now documented: https://airsonic.github.io/docs/jukebox/#using-docker, closing this issue.
