### ISSUE TITLE
"Problem accessing /index.view. Reason: Not found" When accessing airsonic for first time

### ISSUE THREAD

**Issue by KillerCrocs** [airsonic/airsonic#654]
Hello! I've looked up my problem and tried out everything I could find but couldn't get it working.  I'm attempting to install the stand-alone WAR version 10.1.0 on Opensuse Leap 42.3 . Here is the output of Java version and home:
```
admin@linux-vtph:~> java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (IcedTea 3.6.0) (build 1.8.0_151-b12 suse-18.1-x86_64)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
```
```
admin@linux-vtph:~> echo $JAVA_HOME
/usr/lib64/jvm/jre
```

I followed the documentation for setting up the systemd service and that's what I'm currently running it from. But I get an error 404 whenever accessing the site citing that there was a problem accessing /index.view because it was not found. The only thing I changed was the default port to 4040 in /etc/sysconfig/airsonic as this is what subsonic was using earlier and I already had that port open.

Here is the beginning of the log file, I'll add the rest once I get it off my server properly: 

```2017-12-16 10:00:07.395  INFO --- org.airsonic.player.Application          : Starting Application v10.1.0-RELEASE with PID 4214 (/var/airsonic/airsonic.war started by airsonic in /)
2017-12-16 10:00:07.399  INFO --- org.airsonic.player.Application          : The following profiles are active: legacy
2017-12-16 10:00:10.140  INFO --- o.a.p.service.SettingsService            : Java: 1.8.0_151, OS: Linux
2017-12-16 10:00:14.392 ERROR --- net.sf.ehcache.Cache                     : Unable to set localhost. This prevents creation of a GUID. Cause was: linux-vtph: linux-vtph: Name or service not known

java.net.UnknownHostException: linux-vtph: linux-vtph: Name or service not known
        at java.net.InetAddress.getLocalHost(InetAddress.java:1505) ~[na:1.8.0_151]
        at net.sf.ehcache.Cache.<clinit>(Cache.java:217) ~[ehcache-core-2.5.0.jar!/:na]
        at net.sf.ehcache.config.ConfigurationHelper.createCache(ConfigurationHelper.java:303) [ehcache-core-2.5.0.jar!/:na]
        at net.sf.ehcache.config.ConfigurationHelper.createCaches(ConfigurationHelper.java:234) [ehcache-core-2.5.0.jar!/:na]
        at net.sf.ehcache.CacheManager.addConfiguredCaches(CacheManager.java:705) [ehcache-core-2.5.0.jar!/:na]
        at net.sf.ehcache.CacheManager.doInit(CacheManager.java:426) [ehcache-core-2.5.0.jar!/:na]
        at net.sf.ehcache.CacheManager.init(CacheManager.java:352) [ehcache-core-2.5.0.jar!/:na]
        at net.sf.ehcache.CacheManager.<init>(CacheManager.java:237) [ehcache-core-2.5.0.jar!/:na]
        at net.sf.ehcache.CacheManager.create(CacheManager.java:856) [ehcache-core-2.5.0.jar!/:na]
        at net.sf.ehcache.CacheManager.create(CacheManager.java:831) [ehcache-core-2.5.0.jar!/:na]
        at org.airsonic.player.cache.CacheFactory.afterPropertiesSet(CacheFactory.java:51) [classes!/:10.1.0-RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) [spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) [spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) [spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) [spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) [spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) [spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:372) [spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173) [spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067) [spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) [spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) [spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
```

Thanks in advance! Let me know if you need any more information - I tried to make sure I looked at everything first.

**Comment by muff1nman** [comment]
The getLocalHost failure is strange - never seen that before. Can you try the advice [here](https://askubuntu.com/questions/185070/why-do-i-get-hostname-name-or-service-not-known-error#answer-218499):
I.e. whats the output of
```
hostname -fqdn
```

**Comment by KillerCrocs** [comment]
Thank you! This pointed me in the right direction and is not an actual problem with Airsonic at all. I ended up looking at the link you sent and it turns out that the /etc/hosts file had gotten out of whack. Fixed that right up by following the link you sent. This also helped fix an issue I was having with my MS SQL server not connecting to localhost.

**Comment by muff1nman** [comment]
Good to hear and will close this out.
