### ISSUE TITLE
FLAC Exception when scanning media folders.

### ISSUE THREAD

**Issue by epicdistraction** [airsonic/airsonic#661]
I was attempting a scan my media folders on a fresh install of Airsonic 10.1.1 after using Libresonic 6.0.1 for years, and I ran into an error while scraping my database. The Tomcat 8.5.24 instance is up and running on Windows 8.1 with Java 1.8.0_141.

When the media folders are scanned, the log catches this exception when scraping a flac file. I'm able to play the offending file from the Android app and Airsonic interface if I deselect fast access mode. My library was able to be scanned in fast access mode, and it didn't error out on this album when running Libresonic 6.0.1.  If I remove this album from my library and scan again, it will make it a little further to another flac albumn.

```
org.jaudiotagger.audio.exceptions.CannotReadException: Flac Header not found, not a flac file
	at org.jaudiotagger.audio.flac.FlacStreamReader.findStream(FlacStreamReader.java:65) ~[jaudiotagger-2.2.5.jar:na]
	at org.jaudiotagger.audio.flac.FlacInfoReader.read(FlacInfoReader.java:45) ~[jaudiotagger-2.2.5.jar:na]
	at org.jaudiotagger.audio.flac.FlacFileReader.getEncodingInfo(FlacFileReader.java:40) ~[jaudiotagger-2.2.5.jar:na]
	at org.jaudiotagger.audio.generic.AudioFileReader.read(AudioFileReader.java:104) ~[jaudiotagger-2.2.5.jar:na]
	at org.jaudiotagger.audio.AudioFileIO.readFile(AudioFileIO.java:355) ~[jaudiotagger-2.2.5.jar:na]
	at org.jaudiotagger.audio.AudioFileIO.read(AudioFileIO.java:198) ~[jaudiotagger-2.2.5.jar:na]
	at org.airsonic.player.service.metadata.JaudiotaggerParser.getRawMetaData(JaudiotaggerParser.java:86) ~[classes/:10.1.1-RELEASE]
	at org.airsonic.player.service.metadata.MetaDataParser.getMetaData(MetaDataParser.java:47) [classes/:10.1.1-RELEASE]
	at org.airsonic.player.service.MediaFileService.createMediaFile(MediaFileService.java:492) [classes/:10.1.1-RELEASE]
	at org.airsonic.player.service.MediaFileService.checkLastModified(MediaFileService.java:125) [classes/:10.1.1-RELEASE]
	at org.airsonic.player.service.MediaFileService.getChildrenOf(MediaFileService.java:195) [classes/:10.1.1-RELEASE]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:248) [classes/:10.1.1-RELEASE]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:252) [classes/:10.1.1-RELEASE]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:252) [classes/:10.1.1-RELEASE]
	at org.airsonic.player.service.MediaScannerService.doScanLibrary(MediaScannerService.java:188) [classes/:10.1.1-RELEASE]
	at org.airsonic.player.service.MediaScannerService.access$000(MediaScannerService.java:45) [classes/:10.1.1-RELEASE]
	at org.airsonic.player.service.MediaScannerService$2.run(MediaScannerService.java:157) [classes/:10.1.1-RELEASE]

2017-12-24 04:09:44.689  WARN --- o.a.p.s.m.JaudiotaggerParser             : Error when parsing tags in d:\_Music\ARTISTNAME\ALBUMNAME\02 - SONGNAME.flac

... several more failures from same directory ...


2017-12-24 04:09:48.531 ERROR --- o.a.p.s.MediaScannerService              : Failed to scan media library.

org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:619) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:684) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:716) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:726) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:776) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.airsonic.player.dao.AbstractDao.query(AbstractDao.java:103) ~[classes/:10.1.1-RELEASE]
	at org.airsonic.player.dao.AbstractDao.queryOne(AbstractDao.java:179) ~[classes/:10.1.1-RELEASE]
	at org.airsonic.player.dao.MediaFileDao.getMediaFile(MediaFileDao.java:66) ~[classes/:10.1.1-RELEASE]
	at org.airsonic.player.dao.MediaFileDao$$FastClassBySpringCGLIB$$15ad9359.invoke(<generated>) ~[classes/:10.1.1-RELEASE]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738) ~[spring-aop-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) ~[spring-tx-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673) ~[spring-aop-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.airsonic.player.dao.MediaFileDao$$EnhancerBySpringCGLIB$$2dab72c5.getMediaFile(<generated>) ~[classes/:10.1.1-RELEASE]
	at org.airsonic.player.service.MediaFileService.getMediaFile(MediaFileService.java:101) ~[classes/:10.1.1-RELEASE]
	at org.airsonic.player.service.MediaFileService.getMediaFile(MediaFileService.java:78) ~[classes/:10.1.1-RELEASE]
	at org.airsonic.player.service.MediaFileService.findCoverArt(MediaFileService.java:625) ~[classes/:10.1.1-RELEASE]
	at org.airsonic.player.service.MediaFileService.createMediaFile(MediaFileService.java:540) ~[classes/:10.1.1-RELEASE]
	at org.airsonic.player.service.MediaFileService.checkLastModified(MediaFileService.java:125) ~[classes/:10.1.1-RELEASE]
	at org.airsonic.player.service.MediaFileService.getChildrenOf(MediaFileService.java:195) ~[classes/:10.1.1-RELEASE]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:251) [classes/:10.1.1-RELEASE]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:252) [classes/:10.1.1-RELEASE]
	at org.airsonic.player.service.MediaScannerService.doScanLibrary(MediaScannerService.java:188) [classes/:10.1.1-RELEASE]
	at org.airsonic.player.service.MediaScannerService.access$000(MediaScannerService.java:45) [classes/:10.1.1-RELEASE]
	at org.airsonic.player.service.MediaScannerService$2.run(MediaScannerService.java:157) [classes/:10.1.1-RELEASE]
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_141]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_141]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_141]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.8.0_141]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2196) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2229) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2024) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:779) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at sun.reflect.GeneratedConstructorAccessor150.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_141]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.8.0_141]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_141]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_141]
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:153) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:144) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:196) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:159) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	... 27 common frames omitted
Caused by: java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:1.8.0_141]
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:1.8.0_141]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.8.0_141]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.8.0_141]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_141]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_141]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[na:1.8.0_141]
	at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_141]
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	... 46 common frames omitted

2017-12-24 04:09:48.679  INFO --- o.a.p.service.PlaylistService            : Starting playlist import.
2017-12-24 04:09:48.680  INFO --- o.a.p.service.PlaylistService            : Completed playlist import.


```

**Comment by epicdistraction** [comment]
Update, I tried airsonic 10.1.0 to see if it was the new version of jaudiotagger, and it still doesn't work.

**Comment by jooola** [comment]
@epicdistraction You bettter try the latest 10.1.1

**Comment by epicdistraction** [comment]
@jooola As stated in the first post. I attempted 10.1.1 first. Then, I tried 10.1.0 after noticing in the 10.1.1 changelog an update to the jaudiotagger library that is throwing an exception in the log.

**Comment by muff1nman** [comment]
jaudiotagger version was recently updated. This will probably need to be brought up with them.

**Comment by epicdistraction** [comment]
I kept removing offending flac albums from my media library until I was able to get to the next breaking point. This time, no jaudiotagger warnings appeared. Only a mysql commit transaction error. I was thinking the jaudiotagger warnings were causing the severe exception which caused malformed data to be commited, but that's not the case.

Those warnings are correct as those were old flac rips that only included the flac header on the first file in the directory, and the second file to the end were throwing the errors.  The issue may be that airsonic throws a severe exception off the jaudiotagger warning. Although, I should investigate the mysql error before going further down that route. 

Maybe it's trying to mix Connection methods? I'm using the embedded JDBC database type with these values:
JDBC Driver Java classname: com.mysql.jdbc.Driver
JDBC URL : jdbc:mysql://localhost/airsonic?sessionVariables=sql_mode=ANSI_QUOTES
JDBC Username : subsonic
JDBC Password : password

```
2017-12-24 10:25:43.122  INFO --- o.a.p.s.MediaScannerService              : Starting to scan media library.
2017-12-24 10:25:56.033 ERROR --- o.a.p.s.MediaScannerService              : Failed to scan media library.

org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:619) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:684) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:716) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:726) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:776) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.airsonic.player.dao.AbstractDao.query(AbstractDao.java:103) ~[classes/:10.1.0-RELEASE]
	at org.airsonic.player.dao.AbstractDao.queryOne(AbstractDao.java:179) ~[classes/:10.1.0-RELEASE]
	at org.airsonic.player.dao.MediaFileDao.getMediaFile(MediaFileDao.java:66) ~[classes/:10.1.0-RELEASE]
	at org.airsonic.player.dao.MediaFileDao$$FastClassBySpringCGLIB$$15ad9359.invoke(<generated>) ~[classes/:10.1.0-RELEASE]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738) ~[spring-aop-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) ~[spring-tx-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673) ~[spring-aop-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.airsonic.player.dao.MediaFileDao$$EnhancerBySpringCGLIB$$6a3d0359.getMediaFile(<generated>) ~[classes/:10.1.0-RELEASE]
	at org.airsonic.player.service.MediaFileService.createMediaFile(MediaFileService.java:471) ~[classes/:10.1.0-RELEASE]
	at org.airsonic.player.service.MediaFileService.checkLastModified(MediaFileService.java:125) ~[classes/:10.1.0-RELEASE]
	at org.airsonic.player.service.MediaFileService.getChildrenOf(MediaFileService.java:195) ~[classes/:10.1.0-RELEASE]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:248) [classes/:10.1.0-RELEASE]
	at org.airsonic.player.service.MediaScannerService.doScanLibrary(MediaScannerService.java:188) [classes/:10.1.0-RELEASE]
	at org.airsonic.player.service.MediaScannerService.access$000(MediaScannerService.java:45) [classes/:10.1.0-RELEASE]
	at org.airsonic.player.service.MediaScannerService$2.run(MediaScannerService.java:157) [classes/:10.1.0-RELEASE]
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_141]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_141]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_141]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.8.0_141]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2196) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2229) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2024) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:779) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at sun.reflect.GeneratedConstructorAccessor141.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_141]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.8.0_141]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_141]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_141]
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:153) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:144) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:196) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:159) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	... 23 common frames omitted
Caused by: java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:1.8.0_141]
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:1.8.0_141]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.8.0_141]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.8.0_141]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_141]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_141]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[na:1.8.0_141]
	at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_141]
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300) ~[mysql-connector-java-5.1.43.jar:5.1.43]
	... 42 common frames omitted

2017-12-24 10:25:56.105  INFO --- o.a.p.service.PlaylistService            : Starting playlist import.
2017-12-24 10:25:56.106  INFO --- o.a.p.service.PlaylistService            : Completed playlist import.
```

**Comment by epicdistraction** [comment]
Switching to JNDI type seems to have fixed the issue. It's still scanning right now, but I made it past the initial scan and the artist/album tables are being populated in MariaDB.

Could it be this call from the stack trace that sends the media generating functions a bad datasource?

``` 
org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80) ~[spring-jdbc-4.3.12.RELEASE.jar:4.3.12.RELEASE]```

**Comment by jooola** [comment]
We might need to update to jaudiotagger 2.2.6 (when released) since they mention such regression/fixes in the change logs

**Comment by epicdistraction** [comment]
It looks like the owner of the jAudioTagger hasn't made pushing a maven build a priority for a few years now. There are a couple threads about it in their issue tracker.

- [https://bitbucket.org/ijabz/jaudiotagger/issues/67/maven-repository-for-new-versions](https://bitbucket.org/ijabz/jaudiotagger/issues/67/maven-repository-for-new-versions)
- [https://bitbucket.org/ijabz/jaudiotagger/issues/67/maven-repository-for-new-versions](https://bitbucket.org/ijabz/jaudiotagger/issues/231/made-github-repository-for-jaudiotagger)

The work around with jitpack.io and building it off of their repo solved an issue that I was having with unplayable songs, but it appears to have caused another regression that I'm investigating. 

In the dsub android application: if I click on an Artist in the library tab the results are displayed as a plain descending text list. In previous versions, clicking on an artist would display the a small amount of bio about the arists as well as a grid view with the album art being displayed.

I'll dig into the jaudiotagger api to see what changed, and add some unit tests around the library's integration. 

These are the two branches that i'm working off off are available below if any one else is curious.  

This uses a recent commit off jaudiotagger:master
- https://github.com/epicdistraction/airsonic/tree/epicdistraction/jaudiotagger-snapshot

This one uses the 2017-04-06 2.2.6-SNAPSHOT commit.
- https://github.com/epicdistraction/airsonic/tree/epicdistraction/jaudiotagger-2.2.6
