### ISSUE TITLE
Airsonic fails to create "user" table with MariaDB.

### ISSUE THREAD

**Issue by twisp007** [airsonic/airsonic#783]
## Problem description

Airsonic fails to work with MariaDB. Throws this error when trying to create a table called "user": 
```

Aug 20 10:40:46 PC0 java[370]:         at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:299) ~[liquibase-core-3.5.1.jar!/:na]
Aug 20 10:40:46 PC0 java[370]:         ... 116 common frames omitted
Aug 20 10:40:46 PC0 java[370]: Caused by: java.sql.SQLException: Specified key was too long; max key length is 767 bytes
Aug 20 10:40:46 PC0 java[370]: Query is: CREATE TABLE libresonic.user (username VARCHAR(512) NOT NULL, password VARCHAR(512) NOT NULL, CONSTRAINT PK_USER PRIMARY KEY (username))
Aug 20 10:40:46 PC0 java[370]:         at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:113) ~[mariadb-java-client-2.1.2.jar!/:na]
Aug 20 10:40:46 PC0 java[370]:         at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:162) ~[mariadb-java-client-2.1.2.jar!/:na]
Aug 20 10:40:46 PC0 java[370]:         at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:326) ~[mariadb-java-client-2.1.2.jar!/:na]
Aug 20 10:40:46 PC0 java[370]:         ... 118 common frames omitted
Aug 20 10:40:46 PC0 systemd[1]: airsonic.service: Main process exited, code=exited, status=1/FAILURE
Aug 20 10:40:46 PC0 systemd[1]: airsonic.service: Failed with result 'exit-code'.
```

### Steps to reproduce

I added these following lines to `/var/lib/airsonic/airsonic.properties`:

```
DatabaseMysqlMaxlength=512
DatabaseConfigType=EMBED
DatabaseConfigEmbedDriver=com.mysql.jdbc.Driver
DatabaseConfigEmbedPassword=redacted
DatabaseConfigEmbedUrl=jdbc:mysql://localhost/libresonic?sessionVariables=sql_mode=ANSI_QUOTES&useSSL=false
DatabaseConfigEmbedUsername=airsonicdbuser
DatabaseUsertableQuote=
```

I started `airsonic`:

`systemctl start airsonic`

Then `airsonic` fails to start and the above mentioned error shows with `systemctl status airsonic`.

## System information

 * **Airsonic version**:  10.1.2-1
 * **Operating system**:  Manjaro
 * **Proxy server**: Apache
 * **Client**:  Firefox, Chrome, Audinaut

## Additional notes

The default DB system is so bad that any unexpected shutdown leads to database corruption and the application fails to start.

So I am trying to use `MariaDB` with `airsonic`. Please guide me.

**Comment by RIPASSAS** [comment]
This is due to a limitation by MariaDB max characters per key. You need to install MariaDB 10.2 and upwards.

**Comment by RIPASSAS** [comment]
10.1.35-MariaDB
This part is what matters, it should be 10.2 or up.
