### ISSUE TITLE
running tomcat gives permission denied error on first run

### ISSUE THREAD

**Issue by illumilore** [airsonic/airsonic#788]
After following the steps in the install guide, including "sudo chown -R tomcat8:tomcat8 /var/airsonic/" I get permission denied errors when starting tomcat after installing the war

25-Aug-2018 02:40:57.992 SEVERE [localhost-startStop-1] org.apache.catalina.startup.ContextConfig.beforeStart Exception fixing docBase for context [/airsonic]
 java.io.FileNotFoundException: /var/lib/tomcat8/webapps/airsonic.war (Permission denied)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
        at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
        at org.apache.catalina.startup.ExpandWar.expand(ExpandWar.java:90)
        at org.apache.catalina.startup.ContextConfig.fixDocBase(ContextConfig.java:605)
        at org.apache.catalina.startup.ContextConfig.beforeStart(ContextConfig.java:738)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:301)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:395)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:149)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:985)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1856)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

## System information

 * **Airsonic version**: latest
 * **Operating system**: ubuntu 18.04

 * **Proxy server**: * None

**Comment by jooola** [comment]
Be sure that tomcat can read the `airsonic.war` file:

```
sudo chown tomcat8:tomcat8 /var/lib/tomcat8/webapps/airsonic.war
```

**Comment by jooola** [comment]
Yes you're right, I will do this !
