### ISSUE TITLE
JaudiotaggerParser does not support APE files

### ISSUE THREAD

**Issue by RuralHunter** [airsonic/airsonic#865]
## Problem description

When scan APE files, there is error in log:
```
org.jaudiotagger.audio.exceptions.CannotReadException: No Reader associated with this extension:ape
	at org.jaudiotagger.audio.AudioFileIO.readFile(AudioFileIO.java:353) ~[jaudiotagger-2.2.5.jar!/:na]
	at org.jaudiotagger.audio.AudioFileIO.read(AudioFileIO.java:198) ~[jaudiotagger-2.2.5.jar!/:na]
	at org.airsonic.player.service.metadata.JaudiotaggerParser.getRawMetaData(JaudiotaggerParser.java:86) ~[classes!/:10.2.0-SNAPSHOT]
	at org.airsonic.player.service.metadata.MetaDataParser.getMetaData(MetaDataParser.java:47) [classes!/:10.2.0-SNAPSHOT]
	at org.airsonic.player.service.MediaFileService.createSingleFileAlbumChildren(MediaFileService.java:445) [classes!/:10.2.0-SNAPSHOT]
	at org.airsonic.player.service.MediaFileService.updateChildren(MediaFileService.java:406) [classes!/:10.2.0-SNAPSHOT]
	at org.airsonic.player.service.MediaFileService.getChildrenOf(MediaFileService.java:194) [classes!/:10.2.0-SNAPSHOT]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:248) [classes!/:10.2.0-SNAPSHOT]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:252) [classes!/:10.2.0-SNAPSHOT]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:252) [classes!/:10.2.0-SNAPSHOT]
	at org.airsonic.player.service.MediaScannerService.doScanLibrary(MediaScannerService.java:188) [classes!/:10.2.0-SNAPSHOT]
	at org.airsonic.player.service.MediaScannerService.access$000(MediaScannerService.java:45) [classes!/:10.2.0-SNAPSHOT]
	at org.airsonic.player.service.MediaScannerService$2.run(MediaScannerService.java:157) [classes!/:10.2.0-SNAPSHOT]
```
It seems Jaudiotagger does not support APE format and I do not see it supports APE either on its website. However, JaudiotaggerParser claims it [supports APE](https://github.com/airsonic/airsonic/blob/77ca475fbe066b453c75e8614fd738a4667ff252/airsonic-main/src/main/java/org/airsonic/player/service/metadata/JaudiotaggerParser.java#L306) which should not.
I tried FFmpegParser instead and it is successful with APE files. But FFmpegParser currently only claims to support video files. I think it should claims to support APE files.

**Comment by Yetangitu** [comment]
jaudiotagger does not support _ape_, at least not according to the project page:

https://bitbucket.org/ijabz/jaudiotagger

> ...Both a common API and format specific APIs are available, currently supports reading and writing metadata for:
> 
> - Mp3
> - Flac
> - OggVorbis
> - Mp4
> - Aiff
> - Wav
> - Wma
> - Dsf

**Comment by eharris** [comment]
I believe that #1237 should address this.

**Comment by Yetangitu** [comment]
It does. I'm working on getting FFmpegParser to produce usable output for non-video types - the current version used PR #856 _does_ support _ape_ (by claiming all playable types instead of just video types) but it doesn't yet produce any usable metadata. I'll submit a new PR for this feature.
