### ISSUE TITLE
Self-contained JAR broken on master

### ISSUE THREAD

**Issue by fxthomas** [airsonic/airsonic#923]
The self-contained JAR doesn't work on the latest master (9413f1f4).

The UI shows, but JS error messages show up, no file can be played, and the logs contain tons of errors like this one:

```
2019-03-26 21:55:32.114 ERROR --- o.d.servlet.DwrServlet                   : init failed
org.directwebremoting.extend.ContainerConfigurationException: java.lang.IllegalArgumentException: name
        at org.directwebremoting.impl.StartupUtil.createAndSetupDefaultContainer(StartupUtil.java:194) ~[dwr-3.0.2-RELEASE.jar!/:na]
        at org.directwebremoting.servlet.DwrServlet.createContainer(DwrServlet.java:101) ~[dwr-3.0.2-RELEASE.jar!/:na]
        at org.directwebremoting.servlet.DwrServlet.init(DwrServlet.java:64) ~[dwr-3.0.2-RELEASE.jar!/:na]
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:789) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:133) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [na:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at java.base/java.lang.Thread.run(Thread.java:844) [na:na]
Caused by: java.lang.IllegalArgumentException: name
        at java.base/jdk.internal.loader.URLClassPath$Loader.getResource(URLClassPath.java:629) ~[na:na]
        at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:304) ~[na:na]
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:450) ~[na:na]
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:447) ~[na:na]
        at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:446) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566) ~[na:na]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94) ~[airsonic.war:10.3.0-SNAPSHOT]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499) ~[na:na]
        at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
        at java.base/java.lang.Class.forName(Class.java:374) ~[na:na]
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedWebappClassLoader.loadFromParent(TomcatEmbeddedWebappClassLoader.java:93) ~[spring-boot-1.5.18.RELEASE.jar!/:1.5.18.RELEASE]
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedWebappClassLoader.doLoadClass(TomcatEmbeddedWebappClassLoader.java:66) ~[spring-boot-1.5.18.RELEASE.jar!/:1.5.18.RELEASE]
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedWebappClassLoader.loadClass(TomcatEmbeddedWebappClassLoader.java:50) ~[spring-boot-1.5.18.RELEASE.jar!/:1.5.18.RELEASE]
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1156) ~[tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.directwebremoting.util.LocalUtil.classForName(LocalUtil.java:1197) ~[dwr-3.0.2-RELEASE.jar!/:na]
        at org.directwebremoting.impl.DefaultContainer.addParameter(DefaultContainer.java:124) ~[dwr-3.0.2-RELEASE.jar!/:na]
        at org.directwebremoting.impl.StartupUtil.setupDefaults(StartupUtil.java:565) ~[dwr-3.0.2-RELEASE.jar!/:na]
        at org.directwebremoting.impl.StartupUtil.setupDefaultContainer(StartupUtil.java:246) ~[dwr-3.0.2-RELEASE.jar!/:na]
        at org.directwebremoting.impl.StartupUtil.createAndSetupDefaultContainer(StartupUtil.java:189) ~[dwr-3.0.2-RELEASE.jar!/:na]
        ... 20 common frames omitted
```

I traced it back to https://github.com/directwebremoting/dwr/issues/2, and believe it comes from the last DWR update. Not sure what to do here, since the project seems very abandoned.

**Comment by fxthomas** [comment]
(The version we were using before comes from [here](https://github.com/airsonic/airsonic/blob/master/repo/org/directwebremoting/dwr/3.0.rc1/dwr-3.0.rc1.jar) and does not seem available anymore)
