### ISSUE TITLE
Document how to build a working airsonic.war without an IDE

### ISSUE THREAD

**Issue by jvoisin** [airsonic/airsonic#927]
Currently, there is to documentation on how to build the project in the [CONTRIBUTING.md](https://github.com/airsonic/documentation/blob/master/.github/CONTRIBUTING.md ) file. The only documentation that I could find was for [IntelliJ IDEA]( https://github.com/airsonic/documentation/blob/master/developer/intellij/intellij.md ).

I would be nice to have a couple of lines to copy/paste in a terminal, to build a working `.war`, if only to augment the bus factor with regard to producing releases.

**Comment by jooola** [comment]
Did you take a look at the website ? We should have a small documentation in there, maybe this is what you are talking about. https://airsonic.github.io/docs/

**Comment by jvoisin** [comment]
I didn't manage to find anything about building the project :/

**Comment by jooola** [comment]
https://airsonic.github.io/docs/install/source/

**Comment by jvoisin** [comment]
Maybe this could be linked somewhere in the dev' section :)

I tried `mvn clean package`, but it seems that all the javascript files are resulting in an error 500:

```
                        org.directwebremoting.extend.ContainerConfigurationException: java.lang.IllegalArgumentException: name
	at org.directwebremoting.impl.StartupUtil.createAndSetupDefaultContainer(StartupUtil.java:194)
	at org.directwebremoting.servlet.DwrServlet.createContainer(DwrServlet.java:101)
	at org.directwebremoting.servlet.DwrServlet.init(DwrServlet.java:64)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144)
	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:789)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:133)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: name
	at sun.misc.URLClassPath$Loader.getResource(URLClassPath.java:739)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:249)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedWebappClassLoader.loadFromParent(TomcatEmbeddedWebappClassLoader.java:93)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedWebappClassLoader.doLoadClass(TomcatEmbeddedWebappClassLoader.java:66)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedWebappClassLoader.loadClass(TomcatEmbeddedWebappClassLoader.java:50)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1156)
	at org.directwebremoting.util.LocalUtil.classForName(LocalUtil.java:1197)
	at org.directwebremoting.impl.DefaultContainer.addParameter(DefaultContainer.java:124)
	at org.directwebremoting.impl.StartupUtil.setupDefaults(StartupUtil.java:565)
	at org.directwebremoting.impl.StartupUtil.setupDefaultContainer(StartupUtil.java:246)
	at org.directwebremoting.impl.StartupUtil.createAndSetupDefaultContainer(StartupUtil.java:189)
	... 20 more
```

**Comment by jvoisin** [comment]
Oops, there was a mistake on my side, sorry for the noise.

I'll likely send a PR to update a bit the documentation.
