### ISSUE TITLE
Airsonic process/service fails ~20 seconds after startup (java connection errors?) 

### ISSUE THREAD

**Issue by Millichrome** [airsonic/airsonic#979]
## Problem description
After running the provided systemd file (with modification for Ubuntu and a "permission denied" error I was getting), Airsonic starts up but then dies (systemd status changed to failed) after ~20 seconds.

### Steps to reproduce

1. Run `systemctl start airsonic.service`
2. Airsonic initially starts and `systemctl status airsonic.service` returns "active (running)"
3. Wait ~20 seconds
4. `systemctl status airsonic.service` returns "failed" with the following:

~~~
● airsonic.service - Airsonic Media Server
   Loaded: loaded (/etc/systemd/system/airsonic.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2019-04-05 16:32:56 UTC; 2s ago
  Process: 1799 ExecStart=/usr/bin/java $JAVA_OPTS -Dairsonic.home=${AIRSONIC_HOME} -Dserver.context-path=${CONTEXT_PATH} -Dserver.port=${PORT} -jar ${JAVA_JAR} $JAVA_ARGS (code=exited, status=1/FAILURE)
 Main PID: 1799 (code=exited, status=1/FAILURE)

Apr 05 16:32:56 music java[1799]:         at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_191]
Apr 05 16:32:56 music java[1799]:         at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[na:1.8.0_191]
Apr 05 16:32:56 music java[1799]:         at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:153) ~[spring-jdbc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
Apr 05 16:32:56 music java[1799]:         at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:144) ~[spring-jdbc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
Apr 05 16:32:56 music java[1799]:         at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:196) ~[spring-jdbc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
Apr 05 16:32:56 music java[1799]:         at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:159) ~[spring-jdbc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
Apr 05 16:32:56 music java[1799]:         at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388) ~[liquibase-core-3.5.1.jar!/:na]
Apr 05 16:32:56 music java[1799]:         ... 41 common frames omitted
Apr 05 16:32:56 music systemd[1]: airsonic.service: Main process exited, code=exited, status=1/FAILURE
Apr 05 16:32:56 music systemd[1]: airsonic.service: Failed with result 'exit-code'.
~~~

## System information

* Airsonic version: v10.2.1
* OS: Ubuntu 18.04 LTS
* No Proxy server (for now)
* Client: Latest Firefox
* Nothing else installed on the system

I have setup Google firewall to allow incoming data at TCP 8080 (if that even matters).

**Comment by jvoisin** [comment]
You can try to disable one by one the lines in the [systemd unit]( https://github.com/airsonic/airsonic/blob/master/contrib/airsonic.service#L24-L40 ), although it would be sad if one of them was the culprit.

**Comment by Millichrome** [comment]
Trued uncommenting all those options, no luck. Airsonic seems to run a bit longer (~40 sec instead of ~20 sec), but it still dies with the following info:
~~~
Apr 05 18:35:14 music java[3638]:         at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_191]
Apr 05 18:35:14 music java[3638]:         at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[na:1.8.0_191]
Apr 05 18:35:14 music java[3638]:         at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:153) ~[spring-jdbc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
Apr 05 18:35:14 music java[3638]:         at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:144) ~[spring-jdbc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
Apr 05 18:35:14 music java[3638]:         at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:196) ~[spring-jdbc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
Apr 05 18:35:14 music java[3638]:         at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:159) ~[spring-jdbc-4.3.21.RELEASE.jar!/:4.3.21.RELEASE]
Apr 05 18:35:14 music java[3638]:         at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388) ~[liquibase-core-3.5.1.jar!/:na]
Apr 05 18:35:14 music java[3638]:         ... 41 common frames omitted
Apr 05 18:35:14 music systemd[1]: airsonic.service: Main process exited, code=exited, status=1/FAILURE
Apr 05 18:35:14 music systemd[1]: airsonic.service: Failed with result 'exit-code'.
~~~

Is Ubuntu 18.04 a bad option for Airsonic? What would be a good option where the installation would just work out of the box?

**Comment by muff1nman** [comment]
Can you show more of the stack trace?

**Comment by muff1nman** [comment]
Personally I always go for centos. You'll get Java8 out of the box. Ubuntu 18.04 isn't bad but I believe it defaults to a newer jvm version.

**Comment by Millichrome** [comment]
Below is the full log:
~~~
Apr 06 16:55:06 music systemd[1]: Started Airsonic Media Server.
Apr 06 16:55:15 music java[15469]:            _                       _
Apr 06 16:55:15 music java[15469]:      /\   (_)                     (_)
Apr 06 16:55:15 music java[15469]:     /  \   _ _ __  ___  ___  _ __  _  ___
Apr 06 16:55:15 music java[15469]:    / /\ \ | | '__|/ __|/ _ \| '_ \| |/ __|
Apr 06 16:55:15 music java[15469]:   / ____ \| | |   \__ \ (_) | | | | | (__
Apr 06 16:55:15 music java[15469]:  /_/    \_\_|_|   |___/\___/|_| |_|_|\___|
Apr 06 16:55:15 music java[15469]:
Apr 06 16:55:15 music java[15469]:                         10.2.1-RELEASE
Apr 06 16:55:16 music java[15469]: 2019-04-06 16:55:16.178  INFO --- org.airsonic.player.Application          : Starting Applicati
Apr 06 16:55:16 music java[15469]: 2019-04-06 16:55:16.192  INFO --- org.airsonic.player.Application          : The following prof
Apr 06 16:55:22 music java[15469]: 2019-04-06 16:55:22.559  INFO --- o.a.p.service.SettingsService            : Java: 1.8.0_191, O
Apr 06 16:55:23 music java[15469]: 2019-04-06 16:55:23.399  INFO --- org.airsonic.player.Application          : Detected Tomcat we
Apr 06 16:55:33 music java[15469]: 2019-04-06 16:55:33.743 ERROR --- o.a.p.spring.SpringLiquibase             : ==================
Apr 06 16:55:33 music java[15469]: 2019-04-06 16:55:33.748 ERROR --- o.a.p.spring.SpringLiquibase             : An exception occur
Apr 06 16:55:33 music java[15469]: 2019-04-06 16:55:33.749 ERROR --- o.a.p.spring.SpringLiquibase             : A rollback file ha
Apr 06 16:55:33 music java[15469]: 2019-04-06 16:55:33.749 ERROR --- o.a.p.spring.SpringLiquibase             : Execute it within
Apr 06 16:55:33 music java[15469]: 2019-04-06 16:55:33.763 ERROR --- o.a.p.spring.SpringLiquibase             : The exception is a
Apr 06 16:55:33 music java[15469]: liquibase.exception.DatabaseException: java.sql.SQLException: The database is already in use by
Apr 06 16:55:33 music java[15469]:         at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java
Apr 06 16:55:33 music java[15469]:         at org.airsonic.player.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:2
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeI
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initial
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreat
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createB
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBe
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBean
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFa
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBean
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFa
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(Depen
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDepend
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependen
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$Au
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetad
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.po
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populat
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreat
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createB
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBe
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBean
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFa
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateS
Apr 06 16:55:33 music java[15469]:         at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInit
Apr 06 16:55:33 music java[15469]:         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractAppli
Apr 06 16:55:33 music java[15469]:         at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(Embe
Apr 06 16:55:33 music java[15469]:         at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spri
Apr 06 16:55:33 music java[15469]:         at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360
Apr 06 16:55:33 music java[15469]:         at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-b
Apr 06 16:55:33 music java[15469]:         at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuild
Apr 06 16:55:33 music java[15469]:         at org.airsonic.player.Application.main(Application.java:229) [classes!/:10.2.1-RELEASE
Apr 06 16:55:33 music java[15469]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
Apr 06 16:55:33 music java[15469]:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1
Apr 06 16:55:33 music java[15469]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43
Apr 06 16:55:33 music java[15469]:         at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
Apr 06 16:55:33 music java[15469]:         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [airs
Apr 06 16:55:33 music java[15469]:         at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [airsonic.war:10.2
Apr 06 16:55:33 music java[15469]:         at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [airsonic.war:10.2
Apr 06 16:55:33 music java[15469]:         at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) [airsonic.war:
Apr 06 16:55:33 music java[15469]: Caused by: java.sql.SQLException: The database is already in use by another process: org.hsqldb
Apr 06 16:55:33 music java[15469]:         at org.hsqldb.jdbc.Util.sqlException(Unknown Source) ~[hsqldb-1.8.0.7.jar!/:private-200
Apr 06 16:55:33 music java[15469]:         at org.hsqldb.jdbc.jdbcConnection.<init>(Unknown Source) ~[hsqldb-1.8.0.7.jar!/:private
Apr 06 16:55:33 music java[15469]:         at org.hsqldb.jdbcDriver.getConnection(Unknown Source) ~[hsqldb-1.8.0.7.jar!/:private-2
Apr 06 16:55:33 music java[15469]:         at org.hsqldb.jdbcDriver.connect(Unknown Source) ~[hsqldb-1.8.0.7.jar!/:private-2006/09
Apr 06 16:55:33 music java[15469]:         at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_191]
Apr 06 16:55:33 music java[15469]:         at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[na:1.8.0_191]
Apr 06 16:55:33 music java[15469]:         at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverM
Apr 06 16:55:33 music java[15469]:         at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(
Apr 06 16:55:33 music java[15469]:         at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromD
Apr 06 16:55:33 music java[15469]:         at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(Abst
Apr 06 16:55:33 music java[15469]:         at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java
Apr 06 16:55:33 music java[15469]:         ... 41 common frames omitted
Apr 06 16:55:33 music java[15469]: 2019-04-06 16:55:33.767 ERROR --- o.a.p.spring.SpringLiquibase             : ==================
Apr 06 16:55:33 music java[15469]: 2019-04-06 16:55:33.769  WARN --- ationConfigEmbeddedWebApplicationContext : Exception encounte
Apr 06 16:55:33 music java[15469]: 2019-04-06 16:55:33.846 ERROR --- o.s.boot.SpringApplication               : Application startu
Apr 06 16:55:33 music java[15469]: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$Au
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetad
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.po
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populat
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreat
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createB
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBe
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBean
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFa
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateS
Apr 06 16:55:33 music java[15469]:         at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInit
Apr 06 16:55:33 music java[15469]:         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractAppli
Apr 06 16:55:33 music java[15469]:         at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(Embe
Apr 06 16:55:33 music java[15469]:         at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) ~[spr
Apr 06 16:55:33 music java[15469]:         at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360
Apr 06 16:55:33 music java[15469]:         at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-
Apr 06 16:55:33 music java[15469]:         at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuild
Apr 06 16:55:33 music java[15469]:         at org.airsonic.player.Application.main(Application.java:229) [classes!/:10.2.1-RELEASE
Apr 06 16:55:33 music java[15469]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
Apr 06 16:55:33 music java[15469]:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1
Apr 06 16:55:33 music java[15469]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43
Apr 06 16:55:33 music java[15469]:         at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
Apr 06 16:55:33 music java[15469]:         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [airs
Apr 06 16:55:33 music java[15469]:         at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [airsonic.war:10.2
Apr 06 16:55:33 music java[15469]:         at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [airsonic.war:10.2
Apr 06 16:55:33 music java[15469]:         at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) [airsonic.war:
Apr 06 16:55:33 music java[15469]: Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with na
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initial
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreat
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createB
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBe
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBean
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFa
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBean
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFa
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(Depen
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDepend
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependen
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$Au
Apr 06 16:55:33 music java[15469]:         ... 26 common frames omitted
Apr 06 16:55:33 music java[15469]: Caused by: liquibase.exception.DatabaseException: java.sql.SQLException: The database is alread
Apr 06 16:55:33 music java[15469]:         at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java
Apr 06 16:55:33 music java[15469]:         at org.airsonic.player.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:2
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeI
Apr 06 16:55:33 music java[15469]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initial
Apr 06 16:55:33 music java[15469]:         ... 38 common frames omitted
Apr 06 16:55:33 music java[15469]: Caused by: java.sql.SQLException: The database is already in use by another process: org.hsqldb
Apr 06 16:55:33 music java[15469]:         at org.hsqldb.jdbc.Util.sqlException(Unknown Source) ~[hsqldb-1.8.0.7.jar!/:private-200
Apr 06 16:55:33 music java[15469]:         at org.hsqldb.jdbc.jdbcConnection.<init>(Unknown Source) ~[hsqldb-1.8.0.7.jar!/:private
Apr 06 16:55:33 music java[15469]:         at org.hsqldb.jdbcDriver.getConnection(Unknown Source) ~[hsqldb-1.8.0.7.jar!/:private-2
Apr 06 16:55:33 music java[15469]:         at org.hsqldb.jdbcDriver.connect(Unknown Source) ~[hsqldb-1.8.0.7.jar!/:private-2006/09
Apr 06 16:55:33 music java[15469]:         at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[na:1.8.0_191]
Apr 06 16:55:33 music java[15469]:         at java.sql.DriverManager.getConnection(DriverManager.java:208) ~[na:1.8.0_191]
Apr 06 16:55:33 music java[15469]:         at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverM
Apr 06 16:55:33 music java[15469]:         at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(
Apr 06 16:55:33 music java[15469]:         at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromD
Apr 06 16:55:33 music java[15469]:         at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(Abst
Apr 06 16:55:33 music java[15469]:         at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java
Apr 06 16:55:33 music java[15469]:         ... 41 common frames omitted
Apr 06 16:55:34 music systemd[1]: airsonic.service: Main process exited, code=exited, status=1/FAILURE
Apr 06 16:55:34 music systemd[1]: airsonic.service: Failed with result 'exit-code'.
~~~
I did notice a "database in use message," but as far I know I haven't run any other databases. I literally created this instance a few days ago and the only think I've done is follow the airsonic installation guide.

**Comment by jvoisin** [comment]
`java.io.FileNotFoundException: /var/airsonic/db/airsonic.lck (Permission denied)` this is interesting.
Are you sure that he user subsonic is running has has permission to read/write everything in the `/var/airsonic` folder?

**Comment by Millichrome** [comment]
@jvoisin 
Turns out it was permission issue with the /var/airsonic folder. 
Thanks for the help!
