### ISSUE TITLE
Podcast cover art fails to download when special characters appear in the filename

### ISSUE THREAD

**Issue by sfunk1x** [airsonic/airsonic#998]
## Problem description

PodcastService throws exception in airsonic.log when encountering a Podcast channel which has special characters in the cover art filename.

```
2019-04-09 21:07:21.706  WARN --- o.a.p.service.PodcastService             : Failed to download cover art for podcast channel 'Another Way, by Lawrence Lessig': java.lang.IllegalArgumentException: Illegal character in path at index 84: https://equalcitizens.us/wp-content/uploads/powerpress/Another-Way-Podcast-Logo-3000[1].jpg

java.lang.IllegalArgumentException: Illegal character in path at index 84: https://equalcitizens.us/wp-content/uploads/powerpress/Another-Way-Podcast-Logo-3000[1].jpg
	at java.net.URI.create(URI.java:852) ~[na:1.8.0_191]
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:66) ~[httpclient-4.5.6.jar!/:4.5.6]
	at org.airsonic.player.service.PodcastService.downloadImage(PodcastService.java:369) [classes!/:10.2.1-RELEASE]
	at org.airsonic.player.service.PodcastService.doRefreshChannel(PodcastService.java:331) [classes!/:10.2.1-RELEASE]
	at org.airsonic.player.service.PodcastService.access$200(PodcastService.java:72) [classes!/:10.2.1-RELEASE]
	at org.airsonic.player.service.PodcastService$4.run(PodcastService.java:296) [classes!/:10.2.1-RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
Caused by: java.net.URISyntaxException: Illegal character in path at index 84: https://equalcitizens.us/wp-content/uploads/powerpress/Another-Way-Podcast-Logo-3000[1].jpg
	at java.net.URI$Parser.fail(URI.java:2848) ~[na:1.8.0_191]
	at java.net.URI$Parser.checkChars(URI.java:3021) ~[na:1.8.0_191]
	at java.net.URI$Parser.parseHierarchical(URI.java:3105) ~[na:1.8.0_191]
	at java.net.URI$Parser.parse(URI.java:3053) ~[na:1.8.0_191]
	at java.net.URI.<init>(URI.java:588) ~[na:1.8.0_191]
	at java.net.URI.create(URI.java:850) ~[na:1.8.0_191]
	... 10 common frames omitted

```

### Steps to reproduce

1. From Main screen, select Podcasts.
2. Subscribe to a podcast that has special characters in their published cover art filenames.
3. Allow the PodcastService to execute at its configured interval.
4. Watch the airsonic logfile for exceptions during this period.

## System information

 * **Airsonic version**: *10.2.1-RELEASE*
 * **Operating system**: *Ubuntu 18.04.01*
 * **Proxy server**: *PFSense running HAProxy*
 * **Client**: *Chrome; dsub*

## Additional notes

I have what I believe to be a fix and can create a pull request to address the issue. I have a feeling that any other class that downloads art may be impacted by the same behavior, however - I have not delved deeply enough to validate.

**Comment by jvoisin** [comment]
Can you please provide an example podcast url?

**Comment by sfunk1x** [comment]
This is the one that was specifically giving me hassles:

https://equalcitizens.us/wp-content/themes/Divi/podcast.xml

I've also noticed that there are multiple NPEs that pop up when adding a podcast, that are not related to this issue. I've been digging into those as well, but I do have a fix for this ticket and it seems to have been working without issue for the past couple of weeks after adding a few more podcasts. I can create a PR if unit tests are not required.

**Comment by jvoisin** [comment]
Feel free to create a PR :)
